### PR TITLE
submit a pull request: Arthelon

### PR DESCRIPTION
**Pull request by Arthelon**
Great way to get beginners started. Good luck with the rest of GCI!

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@Arthelon, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@Arthelon, thanks for signing the CLA!

**Comment by vaibhavsagar** [comment]
Looks good, merging!

**Comment by vaibhavsagar** [comment]
Thank you! :tada: :sparkles:

**Pull request merged**
