### PR TITLE
Submit a Pull Request

### PR DESCRIPTION
**Pull request by IshanArya**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@IshanArya, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@IshanArya, thanks for signing the CLA!

**Comment by IshanArya** [comment]
Is there anyway to do this straight from the GitHub web interface or do I have to clone it onto my computer and use the CLI?

**Comment by trueskawka** [comment]
Another PR for this was opened at #523

**Pull request closed without merging**
