### PR TITLE
translations: Research translations for Chinese.

### PR DESCRIPTION
**Pull request by 540KJ**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@540KJ, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by trueskawka** [comment]
Hi @540KJ!

Thanks for working on this!

Could you address this point of the task?

> Think about the language used - is it more formal or informal? Are there any specific forms that should or shouldn't be used? What words or phrases are most commonly used? What could sound awkward?

Thanks!

**Comment by trueskawka** [comment]
Hey @540KJ!

I understand you used the table from the Hindi research, but please make sure all your translations are for Chinese.

```
| Name | नाम |
| Password | पासवर्ड |
| Account | खाता |
| Profile | प्रोफ़ाइल |
| See More | और देखें |
| Loading | लोड हो रहा है |
| Notifications | सूचनाएं |
| Activate | सक्रिय करे |
```

Please don't rush through the tasks and make sure they're quality work.

Thanks!

**Comment by 540KJ** [comment]
Hi @trueskawka 

Obviously very embarrassing for me. Think the files should all either be in Chinese or English.

**Comment by trueskawka** [comment]
Cool, thanks for improving @540KJ! Merging :)

**Pull request merged**
