### PR TITLE
Submit a pull request

### PR DESCRIPTION
**Pull request by futuristicblanket**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@futuristicblanket, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@futuristicblanket, thanks for signing the CLA!

**Comment by futuristicblanket** [comment]
No problem, anytime :)

**Comment by TomaszKolek** [comment]
@futuristicblanket Hello!
You're almost there ;-)

You didn't create `hello-world.md` under `futuristicblanket/` directory ;-)
For now you should fix your commits (not create new ones) The thing that will help you is `interactive rebase` - dont hesitate to ask questions - its really important knowledge but not the easies.

Good luck!

**Comment by futuristicblanket** [comment]
Whoops, will fix now

**Comment by futuristicblanket** [comment]
So it was kinda awkies but I semi-figured it out; I managed to use git rebase interactive to change my commits to move the hello-world.md into the futurisitcblanket folder. It then applied the second commit that changed 'username' to 'futuristicblanket'. It didn't; however, remove the original hello-world.md. I did learn how to use git rebase, including how to modify commit messages and 'squash' commits together.

**Comment by showell** [comment]
I am still seeing 10 commits here.  Can you try doing another interactive rebase that has only the two commits that are for this task?  For the sake of getting this task approved, it might be easiest if you just start over here, but it's up to you.

**Comment by TomaszKolek** [comment]
@futuristicblanket Tell me please if am I right:
you did interactive rebase than you executed `git push` and saw an error about `git pull`? 

For now what I'd do it if I were you it'd be:
`git rebase -i HEAD~8` and drop all of unnecessery commits (6 commits) and then run `git push branch_name --force` please also read about push force.

Don't give up - interactive rebase and force pushing are powerful tools but a little bit weird for newbies ;-)

**Comment by futuristicblanket** [comment]
Thanks for the help, I'm pretty sure it worked; however for some reason I am completely unaware of, its messed the commit author up with some bloke called William! How do I fix this?

**Comment by TomaszKolek** [comment]
@futuristicblanket I see you closed the PR - you're trying to do new one?

**Comment by futuristicblanket** [comment]
It's confusing, I wasn't going to try a new one.

**Comment by TomaszKolek** [comment]
Hm. it looks it'd be the best to create new PR for now ;-)

**Comment by futuristicblanket** [comment]
Maybe, I'll give it another 30 minutes, I'll learn more that way.

**Pull request closed without merging**
