### PR TITLE
tushar

### PR DESCRIPTION
**Pull request by tushar-121-patel**
[tushar-121-patel.txt](https://github.com/zulip/zulip-gci/files/654792/tushar-121-patel.txt)

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@tushar-121-patel, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by tushar-121-patel** [comment]
Hai

**Comment by trueskawka** [comment]
Hi Tushar!

Thanks for the pull request.

Could you read the [task description](https://github.com/zulip/zulip-gci/blob/master/tasks/submit-a-pull-request.md) again? Check what your pull request name should be, what commits are expected of you and what changes to the files you should make.

Also, you don't have to open a new pull request each time you want to change what
you've submitted - for future reference you can use
[this guide](https://github.com/zulip/zulip-gci/blob/master/docs/fixing-commits.md)
for fixing your commits.

Thanks!

**Comment by trueskawka** [comment]
Another PR for this was opened at #278

**Comment by trueskawka** [comment]
Hi @tushar-121-patel!

I'm closing this PR, since we haven't heard from you for quite some time.

If you want to still do this task, please reclaim it in the GCI app and comment in this thread so we can reopen the PR.

Thanks :)

**Pull request closed without merging**
