### PR TITLE
Bot avatars B: Create prototype avatars.

### PR DESCRIPTION
**Pull request by joyhchen**
Added 50x50, 100x100, 500x500, and .svg files for customer service, revenue, polling, and error bot icons.

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@joyhchen, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by timabbott** [comment]
Hi @joyhchen!  It looks like you've used `git pull` and ended up with some other folks' code added to your pull request.  You can likely use `git pull --rebase` to clean this up, and then force-push.  The guide in http://zulip.readthedocs.io/en/latest/git-guide.html should help with understanding what's going on, or feel free to ask questions on Zulip :).

**Comment by timabbott** [comment]
This set of avatars is cute!  Definitely looks good in terms of the art.  It'd be great if you can clean up the Git workflow stuff so that we can merge this and mark the task complete.  Thanks @joyhchen!

**Comment by timabbott** [comment]
This looks great, merged!

**Pull request closed without merging**
