### PR TITLE
Submit a pull request

### PR DESCRIPTION
**Pull request by mmiller54**
https://github.com/zulip/zulip-gci/pull/475

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@mmiller54, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@mmiller54, thanks for signing the CLA!

**Comment by umairwaheed** [comment]
@mmiller54, looks good. Can you fix your second commit message?

**Comment by mmiller54** [comment]
Is something wrong with it?

Wysłane z iPhone'a

Dnia 05.01.2017 o godz. 09:10 Umair Khan <notifications@github.com> napisał(a):

**Comment by mmiller54** [comment]
I think that's done 

Wysłane z iPhone'a

Dnia 05.01.2017 o godz. 09:10 Umair Khan <notifications@github.com> napisał(a):

**Comment by krtkmj** [comment]
Just little more work. Change your second commit message from `Update hello-world.md hello-world.md: Change username to GitHub handle.` to `hello-world.md: Change username to GitHub handle. `. Refer [this](https://github.com/zulip/zulip-gci/blob/master/docs/fixing-commits.md) for fixing commit message.

**Comment by trueskawka** [comment]
Another PR for this was opened at #499

**Pull request closed without merging**
