### PR TITLE
Bot Avatars B: Create prototype avatars

### PR DESCRIPTION
**Pull request by ktamashiro18**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@ktamashiro18, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@ktamashiro18, thanks for signing the CLA!

**Comment by reyha** [comment]
@ktamashiro18  Hi, You are almost there! However, a minor change that you can do is amend your commit message to say ``bot avatars: Add prototype avatars.`` instead of ``bot-avatars``. You can use ``git commit --amend`` if this is the last commit that you made. We can merge this once you are done :)

**Comment by umairwaheed** [comment]
Hey @ktamashiro18, nice work. Your PR should have only one commit (https://github.com/zulip/zulip-gci/pull/183/commits/488696e791fad715a77571dd0714f7de8e07e640). You can use `git rebase` to remove all the unwanted commits. 

About the avatars, may be we can make them look sharper by increasing the contrast?

**Comment by trueskawka** [comment]
Hi @ktamashiro18!

I'm closing this PR, since we haven't heard from you for quite some time.

If you want to still do this task, please reclaim it in the GCI app and comment in this thread so we can reopen the PR.

Thanks :)

**Pull request closed without merging**
