### PR TITLE
Submit a Pull Request

### PR DESCRIPTION
**Pull request by ben-klemp**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@ben-klemp, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by trueskawka** [comment]
Hi @ben-klemp!

Could you change the second commit message to `hello-world.md: Change username to GitHub handle.`? Thanks!

Have you claimed the task in the GCI app?

**Comment by ben-klemp** [comment]
Sorry, I am new to GitHub; how do I change a commit message?

**Comment by trueskawka** [comment]
Another PR for this was opened at #225

**Pull request closed without merging**
