### PR TITLE
interactive bots: Run the links bot for dob9601.

### PR DESCRIPTION
**Pull request by dob9601**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@dob9601, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by trueskawka** [comment]
Hi @dob9601!

This looks pretty good!

Could you change the names of your screenshot files so that the whitespaces are instead dashes (`-`) and maybe add some more descriptive names (e.g. `links-bot-pm.png`)?

Also, not a requirement for the task, but you might want to just take screenshots of the application windows, not your desktop - some sensible data may be visible there.

You don't have to open a new PR whenever you want to make some changes. Some helpful docs:

- [Git guide](http://zulip.readthedocs.io/en/latest/git-guide.html)
- [working copies](https://github.com/zulip/zulip-gci/blob/master/docs/working-copies.md)
- [fixing commits](https://github.com/zulip/zulip-gci/blob/master/docs/fixing-commits.md)

Thanks!

**Comment by dob9601** [comment]
@trueskawka losing the will to live here, have had to wait around a day every time this task has been sent back. I will correct the screenshots now....

**Comment by dob9601** [comment]
There is a second commit marking that the screenshots have been corrected. They have been cropped to only show the terminal/browser window and renamed to include no whitespace or upper-case characters

**Comment by TomaszKolek** [comment]
Please read fixing-commits doc and squash two commits into one.
Thanks!

**Comment by dob9601** [comment]
@TomaszKolek Thanks for the fast reply.
I'll get on it now

**Comment by trueskawka** [comment]
Another PR for this was opened at #429

**Pull request closed without merging**
