### PR TITLE
Submit a pull request

### PR DESCRIPTION
**Pull request by cosmicAsymmetry**

### CODE REVIEW

**Comment by timabbott** [comment]
@cosmicAsymmetry congratulations on creating your first pull request!  IT looks like your PR only has one version of hello-world.md; can you try again, this time creating two commits?

**Comment by cosmicAsymmetry** [comment]
Okay. Should I create a new PR for the change?

**Comment by timabbott** [comment]
Yep, you can add additional commits as you get feedback :)

You can also replace the commits on a pull request by doing a git force-push (`git push -f`).  

It looks like this pull request has some extra merge commits that I imagine you didn't create intentionally.  I think this is good enough for the initial task, but I encourage you to play with Git (http://zulip.readthedocs.io/en/latest/git-guide.html will help) and try to figure out how to create a version of this PR without the merge commits.

**Comment by cosmicAsymmetry** [comment]
Will do. Thanks Tim! :smile:

**Pull request closed without merging**
