### PR TITLE
interactive bots: Run the links bot for Mikebarson.

### PR DESCRIPTION
**Pull request by Mikebarson**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@Mikebarson, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by umairwaheed** [comment]
@Mikebarson, can you please include a screenshot which clearly shows what is the output of `@link hello world` and `@links hello world`?

**Comment by trueskawka** [comment]
Hi @Mikebarson!

Could you add a screenshots of messages sent by using `@link` and `@resource`? The bot is supposed to react to those and send them in a PM to the user who posted the messages (which is shown in the screenshot you've added).

Thanks!

**Comment by Mikebarson** [comment]
@trueskawka All done! Please check. Thanks!

**Comment by trueskawka** [comment]
Hm. This is not the right usage for this bot.

Are you using Cordelia's credentials? That's the only way the bot could see private messages between Cordelia and another user.

The bot should respond to messages posted in streams it's subscribed to, not private messages between users since in the production environment it wouldn't have access to the PMs.

Could you send the messages from streams?

Thanks!

**Comment by Mikebarson** [comment]
You mean from the home stream?

**Comment by trueskawka** [comment]
From any stream the bot is subscribed to :)

**Comment by trueskawka** [comment]
Hi @Mikebarson!

What's the status of this PR and your GCI task?

**Comment by Mikebarson** [comment]
@trueskawka I wasn't able to complete this task on time.

**Comment by trueskawka** [comment]
@Mikebarson I think you can reclaim a task you run out of time on. Post a message in this PR if you happen to reclaim it, so we can reopen :)

**Pull request closed without merging**
