### PR TITLE
integrations: Add screenshots and notes for papertrail

### PR DESCRIPTION
**Pull request by anirudhjain75**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@anirudhjain75, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by TomaszKolek** [comment]
@anirudhjain75
1) I'd recommend to try to use rebase instead of creating new PR
2) Please try to do your work on branch not on master (its just good habit)
3) We are not able to accept `.txt` if acceptance criteria from instruction says something different
4) I'm still not able to see your images.

**Comment by anirudhjain75** [comment]
They are in JPEG format.

**Comment by TomaszKolek** [comment]
They are - but still are broken - take a look at your repository - they still are.

**Comment by anirudhjain75** [comment]
I can see them
ill try chrome

**Comment by TomaszKolek** [comment]
Weird, what web-browser are you using?

**Comment by anirudhjain75** [comment]
What do i do then ?

**Comment by TomaszKolek** [comment]
First we need to know where is a problem. Please provide what web browser do you use.

**Comment by anirudhjain75** [comment]
Safari as main

**Comment by TomaszKolek** [comment]
Hm.. So I can confirm - it works.

Let me review it on safari then ;-)

**Comment by TomaszKolek** [comment]
@anirudhjain75 Actually you still need to fix 2 of 3 first points ;-) Lets do it! And ping me after that

**Comment by anirudhjain75** [comment]
What do i have to fix

**Comment by anirudhjain75** [comment]
And i created .mdown file, Is it accepted.

**Comment by TomaszKolek** [comment]
It'd be good to create PR from branch.
I dont see your `.md` file

**Comment by anirudhjain75** [comment]
Ill push it later

**Comment by anirudhjain75** [comment]
.mdown wont be accepted ??

**Comment by TomaszKolek** [comment]
Wont be.

**Comment by anirudhjain75** [comment]
I can submit the same pic format right ?

**Pull request closed without merging**
