### PR TITLE
Submit a Pull Request

### PR DESCRIPTION
**Pull request by hillamu2**
changing 'username' to 'hillamu2'

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@hillamu2, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by femnad** [comment]
For this task there needs to be only two commits, per the task description: https://github.com/zulip/zulip-gci/blob/master/tasks/submit-a-pull-request.md. Could you fix this PR to only have to commits?

**Comment by hillamu2** [comment]
@femnad can you please tell me how to remove the additional commit?

**Comment by femnad** [comment]
You could use the rebase operation: https://github.com/zulip/zulip-gci/blob/master/docs/fixing-commits.md#deleting-old-commits

**Pull request closed without merging**
