### PR TITLE
Interactive bots : Run the links bot for abhayKashyap03

### PR DESCRIPTION
**Pull request by abhayKashyap03**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@abhayKashyap03, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by TomaszKolek** [comment]
I'm a bit disappointed of your notes - it looks you had had no problems - but the chat thread seems you had. Please upgrade your notes.

**Comment by abhayKashyap03** [comment]
Is it OK that I have 2 commits, or should there be only one?

**Comment by TomaszKolek** [comment]
Only one, you should `amend` your commit

**Comment by abhayKashyap03** [comment]
Sorry, I messed this PR. I'll close this and open a new one

**Comment by abhayKashyap03** [comment]
Is that OK?

**Comment by TomaszKolek** [comment]
Its not forbidden but I recommend you to try to "fix" that thing.
Try to understand and use:
[this guide](https://github.com/zulip/zulip-gci/blob/master/docs/fixing-commits.md)

**Comment by abhayKashyap03** [comment]
I did 'git rebase' and squashed commits. Now there is only 1 commit.

**Comment by TomaszKolek** [comment]
Cool! I'm glad to see it.
Could you rename your screenshots to use `_` instead of ` ` (space)?

**Comment by abhayKashyap03** [comment]
Renamed!

**Comment by TomaszKolek** [comment]
It looks great now!
Thanks, @abhayKashyap03 approved and merged.

**Comment by abhayKashyap03** [comment]
Thanks!

**Pull request merged**
