### PR TITLE
discord features set C

### PR DESCRIPTION
**Pull request by jQwotos**
Also available on [GDrive](https://docs.google.com/spreadsheets/d/1HwVlqVNVBAizx1hJ0Uey_Gg3SkDuskDf7w12h89CX-I/edit?usp=sharing)

[GCI Task #5529855623954432](https://codein.withgoogle.com/dashboard/task-instances/5529855623954432/)

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@jQwotos, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by trueskawka** [comment]
Hi @jQwotos!

Have you claimed the task in the GCI app and submitted it for review?

**Comment by jQwotos** [comment]
@trueskawka yea Michael Cordover already accepted it

**Comment by trueskawka** [comment]
Thanks @jQwotos! Closing.

**Pull request closed without merging**
