### PR TITLE
Submit a pull request

### PR DESCRIPTION
**Pull request by futuristicblanket**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@futuristicblanket, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by futuristicblanket** [comment]
I accidentally made the hello-world.md file on the master branch but used a pull request to move it over. Is this ok? I couldn't seem to fix it with git rebase. If I need to fix I can, I'll look into it tomorrow.

**Comment by futuristicblanket** [comment]
@smarx No problem mate, it was a pleasure to sign up to the Dropbox Contributor License Agreement.

**Comment by TomaszKolek** [comment]
I'm happy to see you made great progress! 
Unfortunately, it isn't ok.  You actually did one commit that just makes mess in the commits list, right? I'm saying it to show you why this behavior is not good ;-)

How I'd handle it before doing a merge:
1. Create branch from master by `git checkout -b branchname` it "copies" master under new name
2. Reset master by `git reset --hard HEAD` it resets all local commits (lets say it copies branch from remote) so if you didn't push your commits it should work.
3. Create PR with correct commits ;-)


Ad 2) If you actually did a push you should drop commits and force push - you can read about it in our tutorial: 
https://github.com/zulip/zulip-gci/blob/master/docs/fixing-commits.md


OK, hm... 
I'd create new branch based on this one by command:
`git checkout -b newbranch <HASH>` where <HASH> is you last correct commit
than I would remove branch submit-a-pull-request on remote
```
git branch -d <branch_name>
git push origin --delete <branch_name>
```
next I'd create branch based on `newbranch` and push

Not sure - maybe it's possible to do it better/easier.

**Comment by showell** [comment]
@futuristicblanket If you need more help on this, you can find folks at https://chat.zulip.org/#narrow/stream/GCI.20help to help you.  I am putting the task back to "needs more work."

**Comment by futuristicblanket** [comment]
So when I recreated the branch on GitHub [here](https://github.com/futuristicblanket/zulip-gci/commits/sumbit-a-pull-request) it didn't reopen the pull request. I think I'll need to open another pull request.

**Pull request closed without merging**
