### PR TITLE
interactive bots: Run the followup bot for andrewallen00

### PR DESCRIPTION
**Pull request by andrewallen00**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@andrewallen00, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@andrewallen00, thanks for signing the CLA!

**Comment by vaibhavsagar** [comment]
Note to mentors: I didn't realise that this was a separate pull request and merged these changes as part of #269.

**Comment by vaibhavsagar** [comment]
I'm closing this @andrewallen00, happy to approve a GCI task if there is one.

**Pull request closed without merging**
