### PR TITLE
Submit a pull request

### PR DESCRIPTION
**Pull request by Ethan-N**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@Ethan-N, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@Ethan-N, thanks for signing the CLA!

**Comment by krtkmj** [comment]
Hi @Ethan-N , this PR looks good. But, there is small mistake you did. You need to make a new folder submit-a-pull-request/<username> where <username> is your GitHub username. Put `hello-world.md` inside that folder.

**Comment by Ethan-N** [comment]
@krtkmj is this better?

**Comment by umairwaheed** [comment]
@Ethan-N, can you please make it only two commits? Thanks.

**Comment by Ethan-N** [comment]
Ok, it's all in two commits now, I think it's all good. Thanks!

**Comment by Ethan-N** [comment]
It's all in two commits now, should be good. Thanks!

**Pull request closed without merging**
