### PR TITLE
Bot avatars A: Find avatars from internet sources.

### PR DESCRIPTION
**Pull request by Bolt108**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@Bolt108, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by trueskawka** [comment]
Hi @Bolt108!

Thank you for working on this!

Could you:
- rebase your feature branch,
- have only the one commit required for the task (the hello world commits are only for the "Learn to submit a pull request" task,
- claim and submit the task in the GCI app?

Here are some helpful documents:
http://zulip.readthedocs.io/en/latest/git-guide.html#examine-and-tidy-your-commit-history
https://github.com/zulip/zulip-gci/blob/master/docs/fixing-commits.md

**Comment by Bolt108** [comment]
I made the changes and requested a new pull request #222. I already claimed the task on the GCI app but have yet to submit it for review.

**Comment by reyha** [comment]
Hi, @Bolt108. You can modify the old PR instead of opening a new one that addresses the same issue :). @trueskawka pointed out some really useful resources that might help you with your future submissions.  In case you have any questions, please feel free to ask questions over Zulip chat.

**Comment by reyha** [comment]
Another PR for this was opened at #222.

**Pull request closed without merging**
