### PR TITLE
hello-world.md: Change username to GitHub handle.

### PR DESCRIPTION
**Pull request by vsub2018**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@vsub2018, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by trueskawka** [comment]
Hi @vsub2018!

Thank you for the pull request!

The task requires you to:
- submit a pull request with title "Submit a Pull Request"
- the PR have two commits "Add hello-world.md." and "hello-world.md: Change username to GitHub handle."

Could you examine and tidy your commit history?

Here are some helfpul documents: 
http://zulip.readthedocs.io/en/latest/git-guide.html#examine-and-tidy-your-commit-history
https://github.com/zulip/zulip-gci/blob/master/docs/fixing-commits.md

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@vsub2018, thanks for signing the CLA!

**Comment by trueskawka** [comment]
Another PR for this was opened at #476

**Pull request closed without merging**
