### PR TITLE
Submit a Pull Request

### PR DESCRIPTION
**Pull request by kevv87**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@kevv87, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by mjec** [comment]
It looks like something has gone a bit funny with your commits here and I can't quite figure out what it is. I think it's associated with the branch merge commit. You can drop that commit by doing a `git rebase -i` and dropping the "Merge branch" commit, leaving you with just the two commits we're after.

If you were running into conflicts preventing you from creating a pull request you mgiht have to do a `git pull --rebase`. In order to push back up to github you might also have to do `git push -f`, but see how you go without the `-f` option.

If you run into trouble with any of this, or want more help, you can always chat to us at https://chat.zulip.org/ in the `GCI help` channel.

We'll also need you to sign the Dropbox CLA before this can be approved. You can do that at the link in the comment above (that starts with *Automated message from Dropbox CLA bot*).

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@kevv87, thanks for signing the CLA!

**Comment by trueskawka** [comment]
Another pull request for this was opened at #66

**Pull request closed without merging**
