### PR TITLE
interactive bots: Run the links bot for fredfishgames

### PR DESCRIPTION
**Pull request by fredfishgames**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@fredfishgames, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by trueskawka** [comment]
Hi @fredfishgames!

Great work so far!

Could you make sure your screenshots are consistent? You were supposed to show that the bot responds to `@link` and `@resource` - but the PMs screen is showing messages in response to something else. Please take screenshots of messages send by using `@link` and `@resource` and clearly being reacted to by the links bot - I'd suggest a message different than "hello" or anything you've used before.

Also, could you put the terminal screenshot in a separate file?

Thanks!

**Comment by trueskawka** [comment]
And as for your notes - you requested mentor help on chat, but didn't reflect any problems you've encountered in your notes. Are you sure there was nothing you've had a problem with?

**Comment by fredfishgames** [comment]
Closing Pull request. See the new one here: https://github.com/zulip/zulip-gci/pull/331

**Pull request closed without merging**
