### PR TITLE
add markdown to zulip/zulip repo

### PR DESCRIPTION
**Pull request by lonerz**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@lonerz, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by hackerkid** [comment]
Can you make the commit message more specific?
Have a look at this https://zulip.readthedocs.io/en/latest/version-control.html#commit-messages

**Comment by hackerkid** [comment]
Making a separate commit for this and #351 was not necessary. Can you close #351 and add the commit here?

**Comment by hackerkid** [comment]
I am going to merge this as we don't want to waste the participant's time on this (not an actual GCI task).

**Pull request merged**
