### PR TITLE
interactive bots: Run the followup bot for iandrewt

### PR DESCRIPTION
**Pull request by iandrewt**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@iandrewt, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by trueskawka** [comment]
Hey @iandrewt!

Great work so far!

If you read the code for the followup bot closely, you can see that the message looks good, at line 41:

```      
 new_content = original_content.replace('@followup',
                                               'from %s:' % (original_sender,)) 
```

Could you:
- read the followup bot code to make sure you understand it
- review your notes to reflect that
- send the message for the followup bot to catch from a different stream and take a screenshot?

Thanks!

**Comment by iandrewt** [comment]
Done! Sorry about the delay, time zones...

**Comment by umairwaheed** [comment]
@iandrewt, can you please make it just one commit? This looks good. I think you missed the screenshot against this though:
>excerpt the two lines of code that actually change the contents of the message (to make sure you understand the bot),

**Comment by iandrewt** [comment]
Don't merge this just yet, I'll fix the commit message first

**Comment by showell** [comment]
@iandrewt Thanks for sticking with this task to the bitter end!  Approved and merged!

**Pull request merged**
