### PR TITLE
Uplaod task modifications

### PR DESCRIPTION
**Pull request by TomaszKolek**

### CODE REVIEW

**Comment by showell** [comment]
@timabbott @TomaszKolek These changes look good to me, and I can merge them today if Tim gives me a quick sign off.  I think a good follow up commit might be to add a README somewhere or more comments at the top of these files explaining their purpose (especially since many people will have no idea what "GCI" stands for).   We might want to give the script a more specific name than "upload.py" as well, but this can also be done as a follow-up.

**Comment by rishig** [comment]
Merged, thanks @TomaszKolek and @showell!

**Comment by rishig** [comment]
@TomaszKolek 
Getting the following error when running `python pep8.py` from `scripts/`. Any ideas? 
```
Traceback (most recent call last):
  File "pep8.py", line 2, in <module>
    from upload import upload_task
  File "/home/rishig/zulip-gci/scripts/upload.py", line 2, in <module>
    from .task_uploader.client import GCIAPIClient
ValueError: Attempted relative import in non-package
```

**Comment by TomaszKolek** [comment]
@rishig I actaully didnt test `pep8.py` script (I tested integrations.py). What would happen if you add `__init__.py` to `scripts/` ?

**Comment by rishig** [comment]
hm, adding `__init__.py` didn't work. I don't see an `integrations.py` in master -- do you have something in a branch?

**Comment by TomaszKolek** [comment]
@rishig I don't know what is wrong with it - I googled some solutions but it'd require action from a person who'd execute the script. I pushed a fix and also push one thing that I didn't push last time but its required. Sorry for that!

**Comment by rishig** [comment]
Perfect, that fixed it. Thanks @TomaszKolek!

**Pull request closed without merging**
