### PR TITLE
done as told

### PR DESCRIPTION
**Pull request by malikrhythm2405**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@malikrhythm2405, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by umairwaheed** [comment]
@malikrhythm2405, can you please take a look at your commit messages? They are not correct according to the issue description.

**Comment by malikrhythm2405** [comment]
I added the things as per the guide -- that's correct

**Comment by malikrhythm2405** [comment]
What else should I write

**Pull request closed without merging**
