### PR TITLE
interactive bots: Run the followup bot for sslinebeck

### PR DESCRIPTION
**Pull request by sslinebeck**
[notes.txt](https://github.com/zulip/zulip-gci/files/681341/notes.txt)
botterminal
develmessage
socailmessage
followupmessage

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@sslinebeck, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@sslinebeck, thanks for signing the CLA!

**Comment by umairwaheed** [comment]
@sslinebeck, you need to add these files in your branch and commit them.

**Comment by hackerkid** [comment]
@sslinebeck You have to include the screenshots and note in the pull request. 

> Create a commit with the screenshots and notes, with commit message interactive bots: Run the followup bot for `<username>`..

See https://github.com/zulip/zulip-gci/blob/master/tasks/interactive-bots.md#task-type-a-learn-about-interactive-bots-by-running-the-followup-bot for more details.

If you are not sure how to do that it's better for you to do this task first https://codein.withgoogle.com/dashboard/tasks/6541581402243072/. It has instructions on creating the pull request. 

**Feel free to ask for help if you need by joining the chat -> https://chat.zulip.org**

**Comment by trueskawka** [comment]
Hi @sslinebeck!

How's your task going? Do you need any help?

Could you address @hackerkid's comments on this PR? Thanks!

**Comment by trueskawka** [comment]
Another PR for this was opened at #466

**Pull request closed without merging**
