### PR TITLE
Submit a pull request

### PR DESCRIPTION
**Pull request by smurlafries**
This is the new updated google code-in task.

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@smurlafries, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@smurlafries, thanks for signing the CLA!

**Comment by isht3** [comment]
Hi, @smurlafries you're almost done! You are supposed to make a folder named your username inside the `submit-a-pull-request` folder and put the `hello-world.md` inside that.
Do go throught the task again. https://github.com/zulip/zulip-gci/blob/master/tasks/submit-a-pull-request.md
If you have any questions you can ask us in chat.

**Comment by showell** [comment]
One more thing to do here is to make sure you only have two commits.  If you have questions about git, you can join us at https://chat.zulip.org/

**Pull request closed without merging**
