### PR TITLE
add link to GCI page

### PR DESCRIPTION
**Pull request by lonerz**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@lonerz, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by hackerkid** [comment]
Can you make the commit message more specific?
Have a look at this https://zulip.readthedocs.io/en/latest/version-control.html#commit-messages

**Comment by hackerkid** [comment]
@lonerz You have to change the commit message. Use `git commit --amend` to change the last commit message.

**Comment by lonerz** [comment]
@hackerkid wait darn. I made these commits on Github itself, not through Git... Do I have to rebase my local repo with my origin repo?

**Comment by hackerkid** [comment]
Git fetch the branches from your fork. Then switch to the branch used in PR. Then git amend and force push.

**Comment by lonerz** [comment]
@hackerkid I did ```git fetch --all``` and my new patch branches aren't there... I understand the git amend and force push part however.

**Comment by hackerkid** [comment]
Can you verify the remotes?

**Comment by hackerkid** [comment]
Looks Good. Thanks :)

**Pull request merged**
