### PR TITLE
GCI 2017 tasks

### PR DESCRIPTION
**Pull request by Balaji2198**
Created GCI 2017 tasks.
Updated the files point to correct location.

### CODE REVIEW

**Comment by timabbott** [comment]
This is great but I think we shouldn't copy the tasks from last year that we won't be repeating: eslint, pep8, mypy, chat-app-comparison etc.

**Comment by Balaji2198** [comment]
So shall I remove those files with another commit? Let me know if there are any other changes to be made in these tasks.

**Comment by timabbott** [comment]
We'll do changes separately, since some are a lot of work.  Just remove in
a new commit

-Tim Abbott (mobile)

**Comment by Balaji2198** [comment]
@timabbott  Updated. Kindly review it now.

**Comment by Lyla-Fischer** [comment]
I think that the files Tim mentioned were just examples. We have a list of the tasks that we plan on pulling from last year [here](https://paper.dropbox.com/doc/GCI-tasks-for-2017-Ui8VEQm4UBLAln7ajlggE).

**Comment by Lyla-Fischer** [comment]
lgtm;

**Pull request merged**
