### PR TITLE
Submit a pull request

### PR DESCRIPTION
**Pull request by aabounegm**
The extra 2 commits are because I made a commit to the wrong folder and then reverted it.

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@aabounegm, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@aabounegm, thanks for signing the CLA!

**Comment by hackerkid** [comment]
Could you go over the task description again: https://github.com/zulip/zulip-gci/blob/master/tasks/submit-a-pull-request.md

The pull request should consist only two commits.  Your Pull Request contains some unecessary commits. Please update the pull request to make it contain only 2 commits. Feel free to use this document if you need help in fixing your commits: https://github.com/zulip/zulip-gci/blob/master/docs/fixing-commits.md

Also you may visit [chat.zulip.org](https://chat.zulip.org) if you require further assistance.

**Comment by aabounegm** [comment]
Update: removed the 2 extra commits

**Comment by femnad** [comment]
Could you put the folder named after your username in the folder named as `submit-a-pull-request`?

**Comment by aabounegm** [comment]
How can I move it?

**Comment by aabounegm** [comment]
Ok, I finally did it. I screwed up everything in the process, but fixed it all again

**Pull request merged**
