### PR TITLE
interactive bots: Run the followup bot for fredfishgames

### PR DESCRIPTION
**Pull request by fredfishgames**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@fredfishgames, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by umairwaheed** [comment]
@fredfishgames, can you please make it just one commit? Your screenshots are also not very clear. In your screenshots you need to include the messages you sent from different streams like "devel" and "social".

**Comment by fredfishgames** [comment]
I can't put the commits into one, but I've taken another screenshot. I've taken about 3 hours in total trying to upload to github and 1 hour on the actual task, so is that ok, having more than one commit?

**Comment by fredfishgames** [comment]
New Pull Request: https://github.com/zulip/zulip-gci/pull/328

**Pull request closed without merging**
