### PR TITLE
bot avatars: Add prototype avatars.

### PR DESCRIPTION
**Pull request by cosmicAsymmetry**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@cosmicAsymmetry, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by TomaszKolek** [comment]
@cosmicAsymmetry Tell me please which task you tried to resolved here?

**Comment by krtkmj** [comment]
@cosmicAsymmetry This task requires you to design avatars that can be used in Zulip. See #41 for reference.

**Comment by cosmicAsymmetry** [comment]
Hey @TomaszKolek I'm trying to resolve subtask B.

**Comment by cosmicAsymmetry** [comment]
@krtkmj From what I asked on the Zulip Chat hand sketches were accepted for Sub task B.

**Comment by pweaver** [comment]
@cosmicAsymmetry Can you rebase (rewrite) your commits so just the bot avatar's commit is submitted for merging?

https://zulip.readthedocs.io/en/latest/git-guide.html#examine-and-tidy-your-commit-history should have some instructions on how to do that.

**Comment by cosmicAsymmetry** [comment]
Um... Should I just refork the repo?

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@cosmicAsymmetry, thanks for signing the CLA!

**Pull request closed without merging**
