### PR TITLE
interactive bots: Run the followup bot for Juanvulcano

### PR DESCRIPTION
**Pull request by Juanvulcano**
Hi there! It sounds really fun to build my own interactive bot, looking forward for tasks C and D! 
Thanks! I feel like I'm learning a lot :)

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@Juanvulcano, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by trueskawka** [comment]
Hi @Juanvulcano!

I'm glad you're learning :)

Looking at your messages screenshot, the bot doesn't seem to react to `@follow-up` - could you check that it's true and try to pinpoint why? It might as well be that the bot script is not working properly, if it turns out to be that, please reflect it in your notes.

Also, have you claimed and submitted the task in the GCI app? If yes, could you link it here?

Thanks!

**Comment by Juanvulcano** [comment]
Hi @trueskawka !

It actually works fine, when I reply in a topic with that it will post that to the followup stream, just without the email. I think that is how it should work, shouldn't it?

The followup message actually gives the email

**Comment by Juanvulcano** [comment]
Also, I don't have the task currently claimed, I'm waiting for the approval of another one

**Comment by showell** [comment]
merged, thanks!

**Pull request merged**
