### PR TITLE
https://github.com/zulip/zulip-gci/pull/121

### PR DESCRIPTION
**Pull request by tcehcrhistie**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@tcehcrhistie, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by vaibhavsagar** [comment]
Hi @tcehcrhistie, can you look into using `git rebase` to clean up your commit history? Please have a look at https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request, and don't hesitate to ask us on chat if you have any issues!

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@tcehcrhistie, thanks for signing the CLA!

**Comment by trueskawka** [comment]
Another PR for this was opened at #135

**Pull request closed without merging**
