### PR TITLE
Submit a pull request

### PR DESCRIPTION
**Pull request by xkaygracex**
I'm not sure if it shows that I originally had "Username", then deleted "Username" and added "Kaitlyn Laohoo"

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@xkaygracex, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@xkaygracex, thanks for signing the CLA!

**Comment by xkaygracex** [comment]
Username on GCI is "Kaitlyn Laohoo"

**Comment by feorlen** [comment]
Awesome, thanks!

**Pull request merged**
