### PR TITLE
Submit a pull request

### PR DESCRIPTION
**Pull request by ben-klemp**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@ben-klemp, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@ben-klemp, thanks for signing the CLA!

**Comment by trueskawka** [comment]
Hi @ben-klemp!

Thanks for the pull request!

Could you tidy your commit history to have two commits required in the task?

Here is a helpful guide: https://github.com/zulip/zulip-gci/blob/master/docs/fixing-commits.md

Thanks!

**Comment by trueskawka** [comment]
Another PR for this was opened at #225

**Pull request closed without merging**
