### PR TITLE
Submit a pull request

### PR DESCRIPTION
**Pull request by starrickcrwford**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@starrickcrwford, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by starrickcrwford** [comment]
@smarx Signed the Dropbox CLA.

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@starrickcrwford, thanks for signing the CLA!

**Comment by trueskawka** [comment]
Hi @starrickcrwford!

The first commit is not as described in the task:
> Create a new file called hello-world.md with the following content, verbatim (exactly as written).
> Hello world
> I am username. :tada:

Could you amend your commit? [This doc](https://github.com/zulip/zulip-gci/blob/master/docs/fixing-commits.md) should help.

Thanks!

**Comment by trueskawka** [comment]
Another PR for this was opened at: #532

**Pull request closed without merging**
