### PR TITLE
Submit a Pull Request

### PR DESCRIPTION
**Pull request by abdumuhaimin**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@abdumuhaimin, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by sonali0901** [comment]
@abdumuhaimin  All good just one thing, the task wanted you to create a feature branch `submit-a-pull-request` and then make changes rather than on the master branch of your fork. We avoid disturbing master branch of our repository so as to keep it clean and in sync with the remote master.

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@abdumuhaimin, thanks for signing the CLA!

**Comment by abdumuhaimin** [comment]
do i have to do the whole process again?

**Comment by sonali0901** [comment]
@abdumuhaimin  You can just go ahead and create a new branch from the current master(which has your commits) and then `checkout` to the master again and use `git reset --hard upstream/master` to bring your master to the state as it was originally when you forked.

**Comment by abdumuhaimin** [comment]
I had done a new one. https://github.com/zulip/zulip-gci/pull/148

**Pull request closed without merging**
