### PR TITLE
Bot avatars A: Find avatars from internet sources.

### PR DESCRIPTION
**Pull request by Bolt108**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@Bolt108, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by Bolt108** [comment]
Pull request with changes made from pull request #222.

**Comment by kunall17** [comment]
@Bolt108 Rather than creating new pull request's for your each changes can you please rebase to re-write the commit and force push to the same old repository? 
Refer to this document for more info https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Changing-Multiple-Commit-Messages

**Comment by Bolt108** [comment]
@kunall17 I deleted my old forked repository and forked the repository again when making changes, so this is the only commit. I also closed the other pull request. 

How was I supposed to use Rebase so that I can learn for the future?

 When using git rebase -i HEAD~3 in terminal after changing the prefix words for each commit how am I supposed to save it and progress to the next step?

**Comment by trueskawka** [comment]
@Bolt108 some helpful docs:

- [Git guide](http://zulip.readthedocs.io/en/latest/git-guide.html)
- [working copies](https://github.com/zulip/zulip-gci/blob/master/docs/working-copies.md)
- [fixing commits](https://github.com/zulip/zulip-gci/blob/master/docs/fixing-commits.md)

You should submit the task in the GCI app, so the mentors know what they should review - the flow of reviewing the task is first claiming them in the app, then submitting and waiting for mentor review, then resubmitting them should there be a need for fixes. Could you submit your task in the app?

**Comment by Bolt108** [comment]
@trueskawka Okay, I submitted the task for review!

**Comment by trueskawka** [comment]
Hi @Bolt108!

Thank you for working on this!

Some of your avatars are tiny and I can't say what they're representing - could you make sure it's easy to tell the details at 50x50px?

Also, I think a background here might be useful, since there are a lot of messages in Zulip and a user should stand out a bit more.

@akashnimare @arpith do you have any other thoughts?

**Comment by Bolt108** [comment]
@trueskawka @kunall17  Is my pull request ready to be merged?

**Comment by kunall17** [comment]
@Bolt108 Also can you please squash your commits into one commit? 
You can read more about it here http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by akashnimare** [comment]
@trueskawka looks good to me. My apologies, somehow I missed it 😞

**Comment by trueskawka** [comment]
Hi @Bolt108!

I'm closing this PR, since we haven't heard from you for quite some time.

If you want to still do this task, please reclaim it in the GCI app and comment in this thread so we can reopen the PR.

Thanks :)

**Comment by trueskawka** [comment]
@akashnimare no worries, as soon as @Bolt108 asks for reopening and cleans up the commit history, we can get back to it :)

**Pull request closed without merging**
