### PR TITLE
Submit a pull request

### PR DESCRIPTION
**Pull request by A-Small-Being**
I hope this is correct this time. 

Sorry if it's not

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@A-Small-Being, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by A-Small-Being** [comment]
@smarx I have now signed it

**Comment by arpith** [comment]
Thanks for creating this pull request! Please sign the Dropbox CLA and change the commit messages to `Add hello-world.md.` and `hello-world.md: Change username to GitHub handle.`

You can do this by following the instructions at
https://help.github.com/articles/changing-a-commit-message/#amending-older-or-multiple-commit-messages

Come chat with us at chat.zulip.org and we'll try to help you!

**Comment by A-Small-Being** [comment]
@arpith Hey, sorry but would it be okay if I just re-did it as I am struggling with the git

Thanks

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@A-Small-Being, thanks for signing the CLA!

**Comment by vaibhavsagar** [comment]
Closing since I merged your newer pull request :smile:

**Pull request closed without merging**
