### PR TITLE
Submit a Pull Request

### PR DESCRIPTION
**Pull request by AdmiralZhanghe**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@AdmiralZhanghe, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by AdmiralZhanghe** [comment]
https://github.com/zulip/zulip-gci/pull/508

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@AdmiralZhanghe, thanks for signing the CLA!

**Comment by umairwaheed** [comment]
@AdmiralZhanghe, can you please make sure that there are only two commits in your pull request?

**Comment by sonali0901** [comment]
A new PR #527  was created for the same. So I am closing this one.

**Comment by sonali0901** [comment]
A new PR #527  was created for the same which looks good. So I am closing this one.

**Pull request closed without merging**
