### PR TITLE
Submit a Pull Request

### PR DESCRIPTION
**Pull request by ben-klemp**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@ben-klemp, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by trueskawka** [comment]
Hi @ben-klemp!

This looks great! 

Have you claimed and submitted the task in the GCI app? I'd like to merge this PR and accept your GCI submission.

I can also see you've had some trouble with fixing your commits. Could you read the guides below and get back to us on Zulip, should you have any questions about the git flow?

- [Git guide](http://zulip.readthedocs.io/en/latest/git-guide.html)
- [working copies](https://github.com/zulip/zulip-gci/blob/master/docs/working-copies.md)
- [fixing commits](https://github.com/zulip/zulip-gci/blob/master/docs/fixing-commits.md)

**Comment by ben-klemp** [comment]
I have submitted it on GCI, sorry for the delay.

**Comment by trueskawka** [comment]
Great! Next time please remember to claim a task before you start working on it and submit it for review when you're ready.

Approving and merging.

**Pull request merged**
