### PR TITLE
integrations: Add screenshots and notes for mailchimp.

### PR DESCRIPTION
**Pull request by NoahCristino**
integrations: Add screenshots and notes for mailchimp.

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@NoahCristino, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by NoahCristino** [comment]
Fixed title

**Comment by trueskawka** [comment]
Hi @NoahCristino!

Has this task been submitted and accepted in the GCI app? I'm not sure what's the status.

**Comment by trueskawka** [comment]
Hi @NoahCristino!

I'm closing this PR, since I'm not sure what's the status and there were no changes for more than a month.

If you want to still do this task, please comment in this thread so we can reopen the PR.

Thanks :)

**Pull request closed without merging**
