### PR TITLE
bot avatars: Add prototype avatars.

### PR DESCRIPTION
**Pull request by 1Niels**
Avatars also uploaded to dropbox [here](https://www.dropbox.com/sh/4194mxfwfld5fk0/AADkCZec4vGhxSoC6lId5Dwoa?dl=0)

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@1Niels, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by kevinr** [comment]
Hi Niels, Tim mentioned this on Zulip and you acknowledged it, so I'm just going to mention it here as well so we're tracking it properly, and then toss the task back to you.

> Tim Abbott: @1Niels I don't have much time to look right now (about to go to dinner) but the main thing I worry about is that a lot of the elements aren't really discernable at 50px size (aka the size of your own user avatar at the left side of all the messages you send)
>
> Tim Abbott: So you may want to try to make the main bot element have greater emphasis

**Comment by arpith** [comment]
Hey @1Niels! Thanks for resizing the images. I would suggest changing your avatar on zulip to one of the ones you have uploaded to see what it looks like at 50x50. I've changed mine to zulip-03.png so you can see the issues - do take a look.

My suggestion would be to change the background color so that there is more contrast between the bot and the background like in this sample. You could also try to increase the size of the main feature as done in this sample or perhaps even increase the size of the bot like in this sample

Please do come try your avatars out in zulip! I love your bots and I'm really excited to see where you take this!

**Comment by 1Niels** [comment]
Hey, here is an image of the new avatars in action: 
Zulip Chat Screenshot
Thank you everyone for all your suggestions! I really appreciate the feedback.

**Comment by umairwaheed** [comment]
They look good to me! @arpith, may be you have more suggestions on the design part?

**Comment by kevinr** [comment]
I'm not Arpith, but Umair asked me to weigh in.

These are looking really good.  These work much better at 50px.  I'm still having trouble seeing some of the finer details when I zoom all the way out, though, which is unfortunate because I think they really add character to these icons.

In particular:

* On Bot 1, the black parts of the antennae are getting lost in the purple background.
* On Bots 1 and 2, the lighter yellow details in their crowns are getting lost, which is a shame since I really like them.
* On Bot 2, the whites of its eyes are lost.
* On Bot 3, the electric spark between its antennae is lost.
* On all three bots, the rivets are completely lost.
* I like the way that each bot has a different overall shape -- a triangle, a rounded trapezoid, an off-kilter quadrilateral.  It's harder to see that at 50px though because those shapes meld into the body of the robot.  I think making their necks longer so that the head mass is distinguishable from the body mass will help.

I think exaggerating or reconsidering these details could help make them read better at such a small size.

Really looking forward to the next revision!

**Comment by umairwaheed** [comment]
Thanks a bunch, @kevinr :).

**Comment by trueskawka** [comment]
Hi @1Niels!

Have you looked at @kevinr suggestions?

Also, could you clean up your commit history and make sure all changes are in one commit? Thanks!

**Comment by 1Niels** [comment]
@kevinr wow thanks for all that feedback I really appreciate it! I ended up removing the rivets completely, changes in color and size did more harm than improvement to the avatars. Furthermore I changed the expression of the bot with the triangle shaped head and added a second version with a red light as the "oh no!" version. I hope you like the changes!

**Comment by 1Niels** [comment]
@trueskawka Yes no problem, I just squashed all of the changes into one commit

**Comment by 1Niels** [comment]
@ all mentors, thank you all!

**Comment by umairwaheed** [comment]
@1Niels, they look good. Question: is this file 'bot-avatars/1Niels/zulip_avatars.ai' needed? I think @kevinr will need a look at this.

**Comment by 1Niels** [comment]
@umairwaheed Thanks, I added the file for anyone who wants to make edits as part of [Task type C](https://github.com/zulip/zulip-gci/blob/master/tasks/bot-avatars.md#task-type-c-refine-avatars-from-prototypes)

**Comment by kevinr** [comment]
These are great. I think you can merge these @umairwaheed.

**Comment by kevinr** [comment]
I've gone ahead and merged them. Thanks Niels!

**Comment by umairwaheed** [comment]
Thanks @kevinr.

**Pull request merged**
