### PR TITLE
Submit a Pull Request

### PR DESCRIPTION
**Pull request by Shin4y**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@Shin4y, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@Shin4y, thanks for signing the CLA!

**Comment by trueskawka** [comment]
Hi @Shin4y!

This looks good, althought the changes should've been done on a feature branch `submit-a-pull-request`.

Have you claimed and submitted the task in the GCI app?

**Comment by trueskawka** [comment]
Another PR for this was opened at #169

**Pull request closed without merging**
