### PR TITLE
Submit a Pull Request

### PR DESCRIPTION
**Pull request by A01001000**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@A01001000, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by trueskawka** [comment]
Hi @A01001000!

Could you clean up your commit history to have only the two commits required in the task?

Here are some helpful guides:
- http://zulip.readthedocs.io/en/latest/git-guide.html#examine-and-tidy-your-commit-history
- https://github.com/zulip/zulip-gci/blob/master/docs/fixing-commits.md

Thanks!

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@A01001000, thanks for signing the CLA!

**Comment by trueskawka** [comment]
Another PR for this was opened at #216

**Pull request closed without merging**
