### PR TITLE
submit-a-pull-request  SrijanJha

### PR DESCRIPTION
**Pull request by SrijanJha28**
added hello-world.md file

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@SrijanJha28, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@SrijanJha28, thanks for signing the CLA!

**Comment by TomaszKolek** [comment]
I think in first commit you should just copy and paste text from instruction (not replace username to your name)
but in second commit you should replace it ;-)

Take a look at our tutorial how to fixing existing commits:
https://github.com/zulip/zulip-gci/blob/master/docs/fixing-commits.md
You've to know that creating new commits is not allowed here - you need to modify existing ones.

**Comment by trueskawka** [comment]
Another PR for this was opened at #182

**Pull request closed without merging**
