### PR TITLE
Submit a pull request

### PR DESCRIPTION
**Pull request by aneesh987**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@aneesh987, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@aneesh987, thanks for signing the CLA!

**Comment by krtkmj** [comment]
Hi @aneesh987, please fix your commits. Squash them into two commits. Use [this](https://github.com/zulip/zulip-gci/blob/master/docs/fixing-commits.md) for reference.

**Comment by aneesh987** [comment]
Is this right sir? @krtkmj

**Comment by trueskawka** [comment]
@aneesh987 You need to have only two commits, as per task description.

Some helpful docs:

- [Git guide](http://zulip.readthedocs.io/en/latest/git-guide.html)
- [working copies](https://github.com/zulip/zulip-gci/blob/master/docs/working-copies.md)
- [fixing commits](https://github.com/zulip/zulip-gci/blob/master/docs/fixing-commits.md)

**Pull request closed without merging**
