### PR TITLE
interactive bots: Run the links bot for derAnfaenger.

### PR DESCRIPTION
**Pull request by derAnfaenger**
I finished task B of [this](https://github.com/zulip/zulip-gci/blob/master/tasks/interactive-bots.md#task-type-b-learn-about-interactive-bots-by-creating-a-links-bot).

The first commit contains a small typo fix of the task statement :)

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@derAnfaenger, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by jdherg** [comment]
Hi @derAnfaenger ! Would you mind editing your commit message and PR title from `followup bot` to `links bot` ? Other than that, this looks good to me! Thanks :)

**Comment by derAnfaenger** [comment]
oh, yes, sorry.

**Comment by derAnfaenger** [comment]
both changed.

**Comment by jdherg** [comment]
Thanks and thanks for the typo fix! Approving.

**Comment by derAnfaenger** [comment]
thank you :)

**Pull request merged**
