### PR TITLE
hello-world.md

### PR DESCRIPTION
**Pull request by StioiuDenis**
Hello world
I am username. :tada:

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@StioiuDenis, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@StioiuDenis, thanks for signing the CLA!

**Comment by mjec** [comment]
Hi @StioiuDenis, thanks for signing the Dropbox CLA and submitting a pull request!

There are a couple of things that aren't quite as we would like. What you've done here is create an empty file called `SioiuDenis` inside the `submit-a-pull-request` folder.

In order to complete this task we need you to create a folder called `SioiuDenis` inside the `submit-a-pull-request` folder, and add a file inside `SioiuDenis` called `hello-world.md`. That should have exactly the content shown in the [task description](https://github.com/zulip/zulip-gci/blob/master/tasks/submit-a-pull-request.md).

You'll need to commit that file, then change it to replace the word `username` with your username, and make a second commit. You can then submit a pull request with these commits.

If it helps, you can look at [this example of a completed pull request](https://github.com/zulip/zulip-gci/pull/251).

**Comment by trueskawka** [comment]
Hi @StioiuDenis!

I'm closing this PR, since we haven't heard from you for quite some time.

If you want to still do this task, please reclaim it in the GCI app and comment in this thread so we can reopen the PR.

Thanks :)

**Pull request closed without merging**
