### PR TITLE
Submit a pull request

### PR DESCRIPTION
**Pull request by Mikebarson**
This is my first task completed for the GCI. Hope to learn more!

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@Mikebarson, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by krtkmj** [comment]
Commit looks good. But, you need to fix commit messages.

**Comment by Mikebarson** [comment]
@krtkmj What will I need to change in the commit messages?

**Comment by TomaszKolek** [comment]
https://github.com/zulip/zulip-gci/blob/master/docs/fixing-commits.md
Please read this amazing tutorial.

**Comment by Mikebarson** [comment]
@TomaszKolek I'm a bit confused. What will I need to change in my commit messages?

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@Mikebarson, thanks for signing the CLA!

**Comment by Mikebarson** [comment]
@TomaszKolek Hi! I'm so sorry for this, but I tried the tutorial you gave me but nothing is working. I can't seem to push or pull anything.

**Comment by Mikebarson** [comment]
@TomaszKolek And now I have 4 commits now, and I need to delete all of my commits so that I can create another one.

**Pull request closed without merging**
