### PR TITLE
interactive bots: Run the followup bot for lonerz.

### PR DESCRIPTION
**Pull request by lonerz**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@lonerz, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by trueskawka** [comment]
Hi @lonerz!

Have you claimed and submitted this task in the GCI app? I can't see it under your "completed" or "in progress" tasks.

If you did, could you link it here? Thanks!

**Comment by lonerz** [comment]
@trueskawka yep: https://codein.withgoogle.com/dashboard/task-instances/5235495896350720/

**Comment by showell** [comment]
merged, thanks @lonerz !

**Pull request merged**
