### PR TITLE
Submit a Pull Request

### PR DESCRIPTION
**Pull request by Ch-Developer**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@Ch-Developer, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by sonali0901** [comment]
@Ch-Developer Looks good. Kindly change your commit messages to read `Add hello-world.md` and `hello-world.md: Change username to GitHub handle` . Also, do these changes in a feature branch `submit-a-pull-request` of your fork and not in the `master`.
Feel free to ask if you have any questions.

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@Ch-Developer, thanks for signing the CLA!

**Comment by Ch-Developer** [comment]
Okay I changed it, is it now better? :) https://github.com/zulip/zulip-gci/pull/297

**Comment by reyha** [comment]
Closed! Another PR was opened at #297.

**Pull request closed without merging**
