### PR TITLE
[WIP] task: add first draft of git familiarization task.

### PR DESCRIPTION
**Pull request by vaibhavsagar**
This task description tries to provide a good introduction to `git` for absolute beginners. A couple of issues with it:

1. None of the steps requires using the command line. How do I change this?
2. The materials I've chosen are the best that I'm aware of and they still might not be particularly good. Does anyone have other materials they like?

Feedback please!

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@vaibhavsagar, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by vaibhavsagar** [comment]
How embarrassing :smile:! Signed now.

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@vaibhavsagar, thanks for signing the CLA!

**Comment by arpith** [comment]
Love the task name 😁

**Comment by timabbott** [comment]
@vaibhavsagar should we merge this PR?

**Comment by vaibhavsagar** [comment]
Sorry for the delayed response! I think that might be a good idea, we can always improve it later if required.

**Comment by trueskawka** [comment]
@vaibhavsagar Merging this, so we can improve further :)

**Comment by trueskawka** [comment]
I think this one has been already merged through an interesting glitch in #365 

[Zulip thread](https://chat.zulip.org/#narrow/stream/GCI.20mentors/topic/.23365)

Closing this, since the effort has been already merged and properly attributed :)

**Pull request closed without merging**
