### PR TITLE
interactive bots: Run the links bot for ishankschauhan

### PR DESCRIPTION
**Pull request by ishankschauhan**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@ishankschauhan, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by trueskawka** [comment]
Hi @ishankschauhan!

Glad it worked!

I have only one comment - looking at your terminal output, it seems that you still have the description for the followup bot in your links bot - the instructions on bot usage that appear right after you run the bot ask for writing @followup before the message.

Could you double check that you've changed the comments (`class LinksHandler(object)` and `def usage(self)`)? If you did and the wrong info still appears, could you reflect on that in your notes?

Otherwise, great job!

**Comment by trueskawka** [comment]
Hi @ishankschauhan!

Could you also update your notes, to explain what was the problem?

**Comment by ishankschauhan** [comment]
Done

**Comment by ishankschauhan** [comment]
Done @femnad

**Pull request merged**
