### PR TITLE
Submit a Pull Request

### PR DESCRIPTION
**Pull request by Mikebarson**
This is my first task completed for the GCI. Hope to learn more!

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@Mikebarson, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by TomaszKolek** [comment]
@Mikebarson Please sign the CLA from comment above.

Nice your PR looks pretty good - but you should create specified branch on your fork.
For now you should just create branch froum your current maste `git checkout -b <branch_name>`,
push it and create new PR.

Good luck and dont hesitate to ask! ;-)

**Comment by Mikebarson** [comment]
@TomaszKolek I checked out the CLA but I don't know which type of organization I should use.

Also, what you're saying is that I should create a new branch on my fork? And push my changes there?

**Comment by TomaszKolek** [comment]
Select individual, please.
Yep - probably the task instruction says the branch name ;-)

**Comment by TomaszKolek** [comment]
Also remember about submitting task to review in google code in dashboard

**Comment by Mikebarson** [comment]
Should I put my link to my GCI Dashboard? In the Question field or in the submit for task review?

**Comment by Mikebarson** [comment]
@TomaszKolek  Alright, I've transferred it to submit-a-pull-request branch. Can you check it out?

**Comment by TomaszKolek** [comment]
So first - I'm closing this one.

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@Mikebarson, thanks for signing the CLA!

**Pull request closed without merging**
