### PR TITLE
Submit a Pull Request

### PR DESCRIPTION
**Pull request by 17eparker**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@17eparker, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@17eparker, thanks for signing the CLA!

**Comment by hackerkid** [comment]
Could you go over the task description again: https://github.com/zulip/zulip-gci/blob/master/tasks/submit-a-pull-request.md

The pull request should consist only two commits.  Your Pull Request contains some unecessary commits. Please update the pull request to make it contain only 2 commits. Feel free to use this document if you need help in fixing your commits: https://github.com/zulip/zulip-gci/blob/master/docs/fixing-commits.md

Also you may visit [chat.zulip.org](https://chat.zulip.org) if you require further assistance.

**Comment by trueskawka** [comment]
Hi @17eparker!

I'm closing this PR, since we haven't heard from you for quite some time.

If you want to still do this task, please reclaim it in the GCI app and comment in this thread so we can reopen the PR.

Thanks :)

**Pull request closed without merging**
