### PR TITLE
interactive bots: Run the links bot for dob9601.

### PR DESCRIPTION
**Pull request by dob9601**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@dob9601, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by trueskawka** [comment]
Hi @dob9601!

This looks great! I'm going to merge and approve the task, thanks!

As for your earlier comment about waiting for reviews - we have a queue of students in the GCI app, and we're going through it constantly. We've discussed it a lot on [Zulip](https://chat.zulip.org/) - please join us on chat. You can discuss any doubts or problems with mentors and fellow students.

**Comment by dob9601** [comment]
@trueskawka sorry about me being so rude before, I was getting stressed by the fact that I was submitting a task then getting it sent back for 'more work' a day later which left me with a day of twiddling my thumbs.

**Comment by trueskawka** [comment]
No worries :) I know it can be stressful to not have anyone respond and not having all the information - we're all pretty active on Zulip all the time, so that's the fastest way to get any doubts cleared up ;)

**Pull request merged**
