### PR TITLE
Submit a pull request

### PR DESCRIPTION
**Pull request by Advait-M**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@Advait-M, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@Advait-M, thanks for signing the CLA!

**Comment by vaibhavsagar** [comment]
@Advait-M, can you create your folder as a subfolder of `submit-a-pull-request` and rewrite your commits accordingly? This may involve using `git rebase`

**Comment by Advait-M** [comment]
Modified as requested, thanks for comments.

**Comment by vaibhavsagar** [comment]
Great work @Advait-M! However, now we have 4 commits instead of 2. Can you use `git rebase -i` and `git push --force` to get rid of your first two commits in this pull request?

**Comment by trueskawka** [comment]
Hi @Advait-M!

How's it going? Here is a guide that might help you with fixing your commits - https://github.com/zulip/zulip-gci/blob/master/docs/fixing-commits.md.

**Comment by vaibhavsagar** [comment]
Closing as a newer pull request was accepted.

**Pull request closed without merging**
