### PR TITLE
Submit a Pull Request

### PR DESCRIPTION
**Pull request by toshitabarve**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@toshitabarve, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@toshitabarve, thanks for signing the CLA!

**Comment by umairwaheed** [comment]
@toshitabarve, looks good. Can you please make sure that there are only 2 commits?

**Comment by umairwaheed** [comment]
@toshitabarve, you can use `git rebase` to squash commits. Ask a mentor on Zulip chat if you need help.

**Comment by toshitabarve** [comment]
@umairwaheed I think I messed up the rebasing process, how can I clear the slate and start over?

**Comment by umairwaheed** [comment]
@toshitabarve, just create to required commits in your local repo and then force push using `git push -f origin submit-a-pull-request`.

**Comment by umairwaheed** [comment]
@toshitabarve, looks great. Merging this.

**Pull request merged**
