### PR TITLE
Submit a pull request

### PR DESCRIPTION
**Pull request by abdumuhaimin**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@abdumuhaimin, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by TomaszKolek** [comment]
@abdumuhaimion The result is great! I'd merge it but you did more commits that its needed.
It'd make a  mess in commits history, right? That's just training task so not worry about it ;-)

You should remove unnecessary commits (first and second) in your case I think.
https://github.com/zulip/zulip-gci/blob/master/docs/fixing-commits.md here you can find instruction how to do it.

Dont hesitate to ask us. Good luck!

**Comment by abdumuhaimin** [comment]
how to edit it using git bash? do I have to clone it? i didn't know much on how to use git bash

**Comment by trueskawka** [comment]
Hi @abdumuhaimin!

Have you looked at the file @TomaszKolek linked? There's a whole section on fixing older commits. You can simply do it in the terminal while on your feature branch.

Should you have any questions, could you come chat with us on Zulip?

**Comment by abdumuhaimin** [comment]
yeah. how to fix it using the terminal :(

**Comment by trueskawka** [comment]
Hi @abdumuhaimin!

Can you come and chat with us on [Zulip](https://chat.zulip.org/)?

**Pull request closed without merging**
