### PR TITLE
interactive bots: Run the links bot for jQwotos

### PR DESCRIPTION
**Pull request by jQwotos**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@jQwotos, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by umairwaheed** [comment]
@jQwotos, can you please in your screenshot the output of `@links`?

**Comment by umairwaheed** [comment]
This looks done otherwise. Good job.

**Comment by jQwotos** [comment]
@umairwaheed the image is labeled [Private Message.png](https://github.com/jQwotos/zulip-gci/blob/f7044322b95c0d7c900fa5ee75f27dd0ab928b55/interactive-bots/links/jQwotos/Private%20Message.png)

**Comment by umairwaheed** [comment]
Looks great!

**Pull request merged**
