### PR TITLE
Submit a pull request

### PR DESCRIPTION
**Pull request by starwader**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@starwader, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@starwader, thanks for signing the CLA!

**Comment by umairwaheed** [comment]
@starwader, can you please make sure that there are only two commits in your PR? Thanks.

**Comment by trueskawka** [comment]
Another PR for this was opened at #497

**Pull request closed without merging**
