### PR TITLE
interactive bots: Run the links bot for ausdensk

### PR DESCRIPTION
**Pull request by ausDensk**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@ausDensk, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by TomaszKolek** [comment]
@ausDensk  Looks good, whats the idea of followup screenshot here?

**Comment by ausDensk** [comment]
The task says to try out the bot while the message is still being sent to the followup stream. I took a screenshot of this because I thought you might be interested in it. 😄

**Comment by TomaszKolek** [comment]
I think its not needed - please remove the image and `amend` current commit

**Pull request merged**
