### PR TITLE
Submit a Pull Request

### PR DESCRIPTION
**Pull request by rajbhanushali**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@rajbhanushali, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by feorlen** [comment]
Hi @rajbhanushali, thanks for the pull request. Your changes look great, but it would be better to clean up the history and have only the two changes you wanted.

You can remove those first two commits with an interactive rebase, and then you'll just have the last two good ones. If you need some help with that, you can find us in GCI Help room on https://chat.zulip.org/

**Comment by trueskawka** [comment]
Hi @rajbhanushali! 

How's your work going? Do you need any guidance? Here's some information on how you can fix your commit history - https://github.com/zulip/zulip-gci/blob/master/docs/fixing-commits.md.

Have you claimed the task in the GCI application?

**Comment by trueskawka** [comment]
Hi @rajbhanushali!

I'm closing this PR, since we haven't heard from you for quite some time. 

If you want to still do this task, please reclaim it in the GCI app and comment in this thread so we can reopen the PR.

Thanks :)

**Pull request closed without merging**
