### PR TITLE
Submit a Pull Request

### PR DESCRIPTION
**Pull request by jcstotomas**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@jcstotomas, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by jcstotomas** [comment]
https://github.com/zulip/zulip-gci/pull/492

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@jcstotomas, thanks for signing the CLA!

**Comment by umairwaheed** [comment]
@jcstotomas, can you please make sure that there are only two commits in your pull request? You can use `git rebase` to squash/delete commits.

**Comment by trueskawka** [comment]
Another PR for this was opened at #500

**Pull request closed without merging**
