### PR TITLE
interactive bots: Run the links bot for joyhchen

### PR DESCRIPTION
**Pull request by joyhchen**
Here is my links bot task: https://codein.withgoogle.com/dashboard/task-instances/5740006377259008/

I did this a few days ago but just got around to submitting it now which is why the time stamps on the screenshots are from the weekend.

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@joyhchen, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by hackerkid** [comment]
@joyhchen Can you go through the task description again?

Take screenshots showing that the bot is working, make sure to have screenshots of:

* your terminal window with the bot running, including the command you used to run the bot and the output with the bot description
* messages sent to the bot in the devel and social streams
* messages sent by the bot in the private messages to the author
any other screenshots you find relevant

**Comment by hackerkid** [comment]
@joyhchen Can you go through the task description again?

Take screenshots showing that the bot is working, make sure to have screenshots of:

* your terminal window with the bot running, including the command you used to run the bot and the output with the bot description
* messages sent to the bot in the devel and social streams
* messages sent by the bot in the private messages to the author
any other screenshots you find relevant

**Comment by joyhchen** [comment]
Oh, woops, I didn't look at the updated task description. Gonna edit my screenshots.

**Pull request merged**
