### PR TITLE
Submit a pull request

### PR DESCRIPTION
**Pull request by Toh-Jia-Xin**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@Toh-Jia-Xin, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by arpith** [comment]
Looks good @Toh-Jia-Xin :) Please sign the Dropbox CLA so I can merge this!

**Comment by TomaszKolek** [comment]
@Toh-Jia-Xin  - you should remove the new commits before merge - please read our `in progress` tutorial:
https://github.com/zulip/zulip-gci/blob/fixing-commits-doc/docs/fixing-commits.md

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@Toh-Jia-Xin, thanks for signing the CLA!

**Pull request closed without merging**
