### PR TITLE
Adds hello-world.md

### PR DESCRIPTION
**Pull request by rogersachan**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@rogersachan, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by rogersachan** [comment]
@smarx I have now signed the CLA

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@rogersachan, thanks for signing the CLA!

**Comment by sonali0901** [comment]
@rogersachan  You need to create a PR from a feature branch `submit-a-pull-request` from your fork and not from `master`. We don't want to make any changes in master. Also, edit your PR title to be `Submit a Pull Request`.
For any help, feel free to ask.

**Pull request closed without merging**
