### PR TITLE
Submit a Pull Request

### PR DESCRIPTION
**Pull request by derAnfaenger**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@derAnfaenger, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by trueskawka** [comment]
Hi @derAnfaenger, please sign the Dropbox CLA mentioned in the comment above.

The PR looks good.

**Comment by derAnfaenger** [comment]
@trueskawka  i think i already signed it, didnt't i? how i can check if it recorded my signature? will do it in a feature branch, thank you :)

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@derAnfaenger, thanks for signing the CLA!

**Pull request closed without merging**
