### PR TITLE
Submit a Pull Request

### PR DESCRIPTION
**Pull request by TheGeneralCode**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@TheGeneralCode, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@TheGeneralCode, thanks for signing the CLA!

**Comment by jdherg** [comment]
Hi @TheGeneralCode !
Great start! The content of the commits look great, but you'll need to change the commit messages to meet the guidelines in the instructions. Specifically:

> Add a commit to the `submit-a-pull-request` branch with the changes above,
with commit message `Add hello-world.md.`

for the first commit and 

> Commit the changes you just made with the commit message
`hello-world.md: Change username to GitHub handle.`

for the second.

To learn more about changing commit messages, check out [this guide from GitHub](https://help.github.com/articles/changing-a-commit-message/)

Thanks!

**Comment by trueskawka** [comment]
Hi @TheGeneralCode!

I'm closing this PR, since we haven't heard from you for quite some time.

If you want to still do this task, please reclaim it in the GCI app and comment in this thread so we can reopen the PR.

Thanks :)

**Pull request closed without merging**
