### PR TITLE
interactive bots: Run the followup bot for AZtheAsian

### PR DESCRIPTION
**Pull request by AZtheAsian**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@AZtheAsian, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by TomaszKolek** [comment]
@AZtheAsian I think it looks really good!
Could you please rename your screenshots to use `_` instead of ` ` (space)?

**Comment by AZtheAsian** [comment]
@TomaszKolek I fixed it; I rebased so there's still only one commit

**Comment by jdherg** [comment]
Hi @AZtheAsian ! Would you mind adding a screenshot that shows where the bot is being invoked (the messages that say `@followup`) ? Thanks!

**Comment by AZtheAsian** [comment]
@jdherg added one(though the times are slightly different because `vagrant provision` broke some stuff)

**Pull request merged**
