### PR TITLE
interactive bots: Run the followup bot for ausDensk

### PR DESCRIPTION
**Pull request by ausDensk**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@ausDensk, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by jdherg** [comment]
Hi! Four bits of feedback:

1. The bot should have a different name from the `Cordelia` account to make it clearer which messages are posted by the user as Cordelia and which are posted by the bot.
2. Add a `notes.md` to `note down any places you got stuck, problems or errors you ran into while doing this setup process.` Feel free to also add any other feedback you have on the task, if you didn't have difficulty anywhere.
3. Follow the task filename guidelines for the screenshots (specifically, `Make sure your filenames include no white spaces or underscores, use dashes (-) as connectors.`)
4. When you're done, [squash](https://github.com/zulip/zulip-gci/blob/master/docs/fixing-commits.md#squashing-commits) the commits into one.

Thanks for your submission!

**Comment by umairwaheed** [comment]
@ausDensk can you please also include the output of the message sent from the 'devel' stream? Also, your commit message is missing a space between 'followup bot'.

**Comment by umairwaheed** [comment]
Awesome! Merging this.

**Pull request merged**
