### PR TITLE
Submit a pull request

### PR DESCRIPTION
**Pull request by arpnakumari**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@arpnakumari, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@arpnakumari, thanks for signing the CLA!

**Comment by reyha** [comment]
@arpnakumari Your code looks good. Please change your commit messages to read ``Add hello-world.md`` and ``hello-world.md: Change username to GitHub handle`` as per the task description. You can do an interactive rebase using ``git rebase -i HEAD~n`` to reword your commit messages. 

Please see https://help.github.com/articles/changing-a-commit-message/ for more details.

Kindly let us know if face any difficulty. Thanks!

**Comment by sonali0901** [comment]
@arpnakumari  Great work. You need to now squash your 4 commits into 2 as the task wants. https://github.com/zulip/zulip-gci/blob/master/docs/fixing-commits.md refer this to see how to squash commits.

**Pull request closed without merging**
