### PR TITLE
Submit a pull request

### PR DESCRIPTION
**Pull request by ramon234567**
Pull request

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@ramon234567, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by krtkmj** [comment]
Hi @ramon234567, can you please fix second commit message to `hello-world.md: Change username to GitHub handle.`.

**Comment by ramon234567** [comment]
Is it fixed?

**Comment by trueskawka** [comment]
Hi @ramon234567!

You don't need to open a new PR to apply changes.

Could you clean up your commit history, to make sure there are only two of them, as required in the task? Have you read the document @krtkmj linked?

Another helpful document you could use - [examine and tidy your commit history](http://zulip.readthedocs.io/en/latest/git-guide.html#examine-and-tidy-your-commit-history).

Have you claimed the task in the GCI app?

**Comment by trueskawka** [comment]
Hi @ramon234567!

I'm closing this PR, since we haven't heard from you for quite some time.

If you want to still do this task, please reclaim it in the GCI app and comment in this thread so we can reopen the PR.

Thanks :)

**Pull request closed without merging**
