### PR TITLE
Bot avatars A: Find avatars from internet sources.

### PR DESCRIPTION
**Pull request by anirudhjain75**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@anirudhjain75, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by pweaver** [comment]
The icons look good.

@timabbott The ones under iconarchive are labeled as Freeware. I couldn't find a text of a license. Is that ok?
Also some of the wikipedia ones are CC-SA licenses. I am not sure the interface supports SA. Where would we put copyright attribution?

We should probably update the task to be more clear about licenses.

**Comment by anirudhjain75** [comment]
Yeah they are safe

**Comment by anirudhjain75** [comment]
I have searched icons only whose licence give full allowance

**Comment by pweaver** [comment]
Licenses tend to be complicated. We can't actually use all open licenses because some of them have terms we can't follow. For example I am discussing with mentors about whether we can use a CC-SA license because the SA requires attribution to the author and we might not support putting a copyright somewhere. (But we might I am not sure)

Can you add which license each image is licensed under in the notes. Then I will approve. merge in the pull request.

**Comment by anirudhjain75** [comment]
Can I make a edit URLs.txt commit

**Comment by pweaver** [comment]
When you edit the files you can use `git commit --amend` to commit them and it will just update the previous commit. Then you can do `git push -f` (the -f will force an update) to update the branch.

**Pull request merged**
