### PR TITLE
Submit a pull request

### PR DESCRIPTION
**Pull request by ThatGuy1426**
This is my 'Submit a pull request task' :).

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@ThatGuy1426, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@ThatGuy1426, thanks for signing the CLA!

**Comment by krtkmj** [comment]
@ThatGuy1426 Please squash your second and third commits. You can refer [this doc](https://github.com/zulip/zulip-gci/blob/master/docs/fixing-commits.md) for instructions on squashing commits.

**Comment by trueskawka** [comment]
Hi @ThatGuy1426!

I'm closing this PR, since we haven't heard from you for quite some time.

If you want to still do this task, please reclaim it in the GCI app and comment in this thread so we can reopen the PR.

Thanks :)

**Pull request closed without merging**
