### PR TITLE
hello-world.md: Change zahariasp to GitHub handle.

### PR DESCRIPTION
**Pull request by zahariasp**
hello-world.md: Change zahariasp to GitHub handle.

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@zahariasp, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by isht3** [comment]
Hi, there @zahariasp You're pull request is supposed to be consist of two commits, just go through the task again https://github.com/zulip/zulip-gci/blob/master/tasks/submit-a-pull-request.md.
If you need any help do ask us in the chat. You can refer this for fixing commits. https://github.com/zulip/zulip-gci/blob/master/docs/fixing-commits.md

**Comment by zahariasp** [comment]
I have made the file and change the username in one step then I made 1 pull request ... where is the problem?

**Comment by zahariasp** [comment]
I have made the file and changed the username in 1 step then I made a pull request only one ... where is the problem when the task is full?

**Comment by sonali0901** [comment]
@zahariasp  Kindly go through the task description again, you need to add the file with original content and make a commit, edit the file to add your handle and make the second commit. Also you need to work on a feature branch `submit-a-pull-request`. Plus, your pull request should be titled `Submit a pull request`

**Pull request closed without merging**
