### PR TITLE
Submit a Pull Request

### PR DESCRIPTION
**Pull request by bigdavisc**
:)

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@bigdavisc, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@bigdavisc, thanks for signing the CLA!

**Comment by TomaszKolek** [comment]
@bigdavisc  That's nice to see you and your contribution here! :-)

One point you should do is to remove first 2 commits (they are necessery)
Please try to execute commands:
`git rebase -i HEAD~4`
change first two `pick` to `d` stands for drops
than save your changes
and execute `git push branch_name --force`

Dont hesitate to ask if you'll meet any problems.
I actually did interactive rebase ;-) Read about it!

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@bigdavisc, thanks for signing the CLA!

**Comment by bigdavisc** [comment]
@TomaszKolek Fixed. Thank You

**Comment by showell** [comment]
Looks good!  I am about to approve the task now, and I will merge it soon.

**Pull request closed without merging**
