### PR TITLE
interactive bots: Run the links bot for dob9601

### PR DESCRIPTION
**Pull request by dob9601**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@dob9601, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by umairwaheed** [comment]
@dob9601, you need to create just one bot. That bot should be able to handle '@links' and '@resource' commands.

**Comment by dob9601** [comment]
@dob9601 there is only one bot, it's just that there are some logs from a previous task. I will change up the code so it responds to @links instead of @link

**Comment by hackerkid** [comment]
Could you go over the task description again. The pull request should consist only 1 commit.  Your Pull Request contains some unecessary commits. Please update the pull request to make it contain only 1 commit. Feel free to use this document if you need help in fixing your commits: https://github.com/zulip/zulip-gci/blob/master/docs/fixing-commits.md

Also you may visit [chat.zulip.org](https://chat.zulip.org) if you require further assistance.

**Comment by dob9601** [comment]
@hackerkid those excess commits were due to the fact that I had to redo the screenshots. I will delete this branch and create a new branch.

**Comment by hackerkid** [comment]
@dob9601 Why don't you squash all these commits into one and force push into the branch?

**Comment by dob9601** [comment]
@hackerkid it's a short branch, id rather start it fresh and get it 100% right then have to wait another 5 hrs to only get it sent back with 'needs more work'

**Comment by trueskawka** [comment]
Another pull request for this was opened at #424.

**Pull request closed without merging**
