### PR TITLE
Submit a Pull Request

### PR DESCRIPTION
**Pull request by PySq**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@PySq, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@PySq, thanks for signing the CLA!

**Comment by sonali0901** [comment]
@PySq  The commits look great. We want you to make these changes in a feature branch `submit-a-pull-request` in your fork and not in the master. You wouldn't want to make changes in your `master`. So you need to create a PR from your feature branch and not master.
Feel free to ask anything,

**Comment by reyha** [comment]
Closed! Another PR was opened at #296.

**Pull request closed without merging**
