### PR TITLE
Bot avatars B: Create prototype avatars.

### PR DESCRIPTION
**Pull request by derAnfaenger**
The GCI task on this can be found here: https://codein.withgoogle.com/dashboard/task-instances/5935443218530304/
The Zulip discussion on this can be found here: https://chat.zulip.org/#narrow/stream/GCI.20tasks/topic/Design.20a.20collection.20of.20avatars.20for.20Zulip.20bots

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@derAnfaenger, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by trueskawka** [comment]
Hi @derAnfaenger!

Those look pretty good! They're consistent and simple enough to be used in smaller versions.

A few comments:
- The details on bots 1 and 2 are a little bit hard to see in the smaller version - maybe try to make the lines bolder and remove some of them? Especially the squiggles on the piece of paper are hard to discern.
- I'm not sure if the third bot needs eyes, maybe you could use just cogs? It gets a bit crowded there ;)

Could you ponder about those and implement if you agree with them?

@arpith do you have any other comments?

**Comment by derAnfaenger** [comment]
@trueskawka applied all your suggestions :)

**Comment by umairwaheed** [comment]
@derAnfaenger, you probably want to remove that extra empty space and make your avatars bigger. Maybe add more contrast?

**Comment by derAnfaenger** [comment]
@umairwaheed made all the avatars bigger (as big as possible, no space between horizontal borders and bots) and added some contrast by making the lines even thicker and changing the color of the mouths.

**Pull request merged**
