### PR TITLE
Add hello-world.md

### PR DESCRIPTION
**Pull request by PVachher**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@PVachher, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by TomaszKolek** [comment]
Hello @PVachher, please sign CLA first.

Also please read once again an instruction - the effect of your work is great but in the middle you forgot about making 2 commits - thats one of our Acceptance Criteria. Please fix it ;-) 
https://github.com/zulip/zulip-gci/blob/master/docs/fixing-commits.md
It might be helpful

**Comment by TomaszKolek** [comment]
Please remember that here we need to have 2 commits - not more and not less ;-)

**Comment by PVachher** [comment]
I have done 3 commits
1. Username
2. Default File Addition
3. Username

Hope it will be alright

**Comment by PVachher** [comment]
@TomaszKolek I have signed the CLA.

**Comment by TomaszKolek** [comment]
Sorry, it isn't. In a real big project its not good behavior because you actually did a mess in commits list ;-) Here its just a training so lets train and try to do in 2 correct commits ;-) 
Lets read the doc from url I send in my previous comment ;-)

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@PVachher, thanks for signing the CLA!

**Pull request closed without merging**
