### PR TITLE
Submit a Pull Request

### PR DESCRIPTION
**Pull request by gunvirranu**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@gunvirranu, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by showell** [comment]
Hi @gunvirranu, this looks pretty good, but one detail that needs to be fixed is that these files should be in a directory called submit-a-pull-request.  If you re-read the task, I think you'll see what I mean.  https://github.com/showell/zulip-gci/blob/master/tasks/submit-a-pull-request.md

If you need help fixing this, please join the Zulip chat at https://chat.zulip.org/#narrow/stream/GCI.20help

**Comment by gunvirranu** [comment]
@showell, I believe I have fixed the problem. Thanks!

**Comment by sonali0901** [comment]
@gunvirranu  Looks great! Hope to see some more submissions.

**Pull request merged**
