### PR TITLE
Submit a pull request

### PR DESCRIPTION
**Pull request by parth222**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@parth222, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by TomaszKolek** [comment]
Your commit messages dont look as in task description probably.
Also your file has more lines that it should have. 
Please read https://github.com/zulip/zulip-gci/blob/master/docs/fixing-commits.md and fix commits ;-) Good luck

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@parth222, thanks for signing the CLA!

**Comment by TomaszKolek** [comment]
You cannot add new commits, please update existing ones

**Comment by krtkmj** [comment]
@parth222 Please fix your second commit message to `hello-world.md: Change username to GitHub handle.`. Remove `Update hello-world.md` from commit message. Refer https://github.com/zulip/zulip-gci/blob/master/docs/fixing-commits.md for fixing commit message.

**Comment by showell** [comment]
Hi @parth222.  I am going to approve this task, but for future tasks, please read the description more carefully.  For this particular task, we asked you to create the files in a subdirectory.  If you have problems with future tasks, mentors can help you on https://chat.zulip.org/#narrow/stream/GCI.20help

**Pull request closed without merging**
