### PR TITLE
Create Hello-World.md

### PR DESCRIPTION
**Pull request by anirudhjain75**
hello-world.md: Change username to GitHub handle.

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@anirudhjain75, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by anirudhjain75** [comment]
@smarx What should i chose organisation or  individual

**Comment by anirudhjain75** [comment]
@smarx I already have an Individual registration

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@anirudhjain75, thanks for signing the CLA!

**Comment by TomaszKolek** [comment]
@anirudhjain75 The idea of this task was to teach you how to create a branch, work with commits and create PR.
You are really close to complete this task but one of the points was to create 2 commits as you can see in the tutorial. Please try to fix it in this PR - or if you'd have any problems - ask here or on our chat.

**Pull request closed without merging**
