### PR TITLE
Sumbit a pull request

### PR DESCRIPTION
**Pull request by futuristicblanket**
This is a clone of PR #77 as I had to delete the branch.

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@futuristicblanket, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by TomaszKolek** [comment]
Whoa! I'm happy that you did it! Please submit your task in GCI Dashboard

**Comment by futuristicblanket** [comment]
Done, I think?

**Comment by TomaszKolek** [comment]
Nope, I see you submitted the task and next claimed it again.

**Comment by futuristicblanket** [comment]
Yeah, I just noticed that, whoops. Should be fixed now.

**Comment by futuristicblanket** [comment]
Thank you very much. Even though I stuffed it up a couple of times, I'd say it was a success as I learnt quite a bit more on using git.

**Pull request merged**
