### PR TITLE
tushar

### PR DESCRIPTION
**Pull request by tushar-121-patel**
hello I am tushar patel. I Studied in class 12. I am a participant of google code in.I am on the task of zulip of creating a pull request on git hub

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@tushar-121-patel, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by TomaszKolek** [comment]
@tushar-121-patel Please read the task description again - files you committed are completely different.

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@tushar-121-patel, thanks for signing the CLA!

**Comment by sonali0901** [comment]
@tushar-121-patel  Read the task carefully. https://github.com/zulip/zulip-gci/blob/master/tasks/submit-a-pull-request.md
If you need any help in understanding what is expected, feel free to ask us at [Zulip](https://zulip.tabbott.net/#narrow/stream/GCI.20help)

**Comment by trueskawka** [comment]
Another PR this was opened at #276

**Pull request closed without merging**
