### PR TITLE
Merge german translation docs.

### PR DESCRIPTION
**Pull request by derAnfaenger**
Merge the german translation docs 'general-notes.md' and
'special-terms.md' into one translation guide 'german.md'.

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@derAnfaenger, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by trueskawka** [comment]
Hey @derAnfaenger!

I meant a PR for the main Zulip repo, so we can publish the translation style guide for German :)

**Comment by derAnfaenger** [comment]
@trueskawka ooh, I see. I though we'd discuss and merge it here first and then make a new PR for the main style guide. 
Will close this one then and reopen one for zulip :)

**Comment by trueskawka** [comment]
Cool, thanks :)

**Pull request closed without merging**
