### PR TITLE
Remove showell/hello-world.md.

### PR DESCRIPTION
**Pull request by showell**
(I added showell/hello-world.md in a prior commit, but this
was just to help a colleage practice merging.  This commit
removes the unneeded file.)

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@showell, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by feorlen** [comment]
Hi @showell, your pull request looks good! I'll merge it.

**Comment by feorlen** [comment]
Done, thanks!

**Comment by showell** [comment]
Thanks for merging my change!

**Pull request merged**
