### PR TITLE
Submit a pull request

### PR DESCRIPTION
**Pull request by kalpana2k1**
Hello,

My name is Kalpana. I have completed this beginner task. Can anyone please review it from the community?

Thank you!

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@kalpana2k1, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by kalpana2k1** [comment]
Thank you smarx I have signed the Dropbox CLA,

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@kalpana2k1, thanks for signing the CLA!

**Comment by TomaszKolek** [comment]
Hello @kalpana2k1 I think your `.md` file should be under directories:
`submit-a-pull-request/<name>/hello-world.md` not only `<name>/hello-world.md`

**Comment by TomaszKolek** [comment]
You should change your first and second commit (not make new one)
https://github.com/zulip/zulip-gci/blob/master/docs/fixing-commits.md
here is an instruction how to do it

**Comment by kalpana2k1** [comment]
Hello @TomaszKolek I need to create a parent folder called "submit-a-pull-request" in the branch right? Let me fix this. Should I open a new pull request?

**Comment by kalpana2k1** [comment]
I will open a new pull request in a few minutes.

**Pull request closed without merging**
