### PR TITLE
interactive bots: Run the followup bot for peguin40 (GCI name: Ang Sw…

### PR DESCRIPTION
**Pull request by peguin40**
…ee Chow)

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@peguin40, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by trueskawka** [comment]
Hi @peguin40!

This looks great!

I have only two minor issues:
- Could you rename the screenshots so that the names have no whitespaces or underscores? Please replace all underscores and whitespaces with  `-` (dashes).
- Why did you add the `___init___.py` in your PR? Could you remove it from your commit?

Thanks!

**Comment by peguin40** [comment]
Sorry, I'm not really that acquainted with the github system yet. I added __init__.py as explained in my notes.md file because a obsolete version for python 2 was provided and I had to edit it in order for it to work properly with python 3. I thought you might be interested in taking a look at it and improving the experience for other users.

**Comment by trueskawka** [comment]
Ah, sorry, read the notes but didn't notice the one about attaching the actual file.

I think this might be a good opportunity for you to learn about the git flow and using GitHub.
 
Some helpful docs:

- [Git guide](http://zulip.readthedocs.io/en/latest/git-guide.html)
- [working copies](https://github.com/zulip/zulip-gci/blob/master/docs/working-copies.md)
- [fixing commits](https://github.com/zulip/zulip-gci/blob/master/docs/fixing-commits.md)

Could you read those and review and refine your commit history? This pull request should have just one commit.

Thanks!

**Comment by peguin40** [comment]
Yea, one of the mentors last year asked me to squash commits together but I sort of forgot how. Thanks for the resources!

**Comment by trueskawka** [comment]
Could you re-add the `___init___.py` it while reviewing your commits? We'll definitely want to review it separately, maybe even create an issue and a task for that.

**Comment by peguin40** [comment]
so I don't delete it?

**Comment by peguin40** [comment]
are the commits all merged into one now? or did I do it wrongly?

**Comment by TomaszKolek** [comment]
@peguin40 No they aren't ;-(.
Please read fixing commits from @trueskawka comment - it should help a lot.

**Comment by peguin40** [comment]
I don't know what I did but I ended up with this. 1 squashed commit left. Is this correct? XD

**Comment by mjec** [comment]
@peguin40 this squashed commit looks good! We'll have to figure out what was happening with `__init.py__` but for now I'll approve your task

**Comment by trueskawka** [comment]
@showell Bumping this - could you look at the `__init.py__` issues? :)

**Comment by showell** [comment]
@trueskawka I'm not sure what's really going on with the egg-related issues, but I think it might be a Windows-specific problem, so I'm happy to just be aware of it for now, but not take further action.  Since the task is approved, I am going to go ahead and merge this to zulip-gci.

**Pull request merged**
