### PR TITLE
Submit a Pull Request

### PR DESCRIPTION
**Pull request by muhammednagy**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@muhammednagy, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@muhammednagy, thanks for signing the CLA!

**Comment by TomaszKolek** [comment]
In general looks good, but you should create feature branch (with the name as described in tutorial), push commits there and make PR.

Good luck!

**Comment by reyha** [comment]
Closed! Another PR was opened at #370.

**Pull request closed without merging**
