### PR TITLE
Submit a pull request

### PR DESCRIPTION
**Pull request by william1835**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@william1835, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@william1835, thanks for signing the CLA!

**Comment by trueskawka** [comment]
Hi @william1835 - your hello.md file doesn't seem to have content. 

Also, the task requires you to have two commits:

- `Add hello-world.md.` that adds the required file

- `hello-world.md: Change username to GitHub handle.` that changes the file

Could you cleanup your commits to match the requirements? Thanks!

**Comment by william1835** [comment]
I had already completed the task, and have committed the changes **(https://github.com/zulip/zulip-gci/pull/31)**. However I am now moving the file to the correct place

**Comment by trueskawka** [comment]
Ok, thanks for clearing it up!

**Comment by william1835** [comment]
@trueskawka Sorry for the long length of time for a reply. This is a real rookie question, but how do I do that?

**Comment by trueskawka** [comment]
Hi @william1835!

Sorry, your messaged got a bit lost in my feed.

Here are some docs on how to fix your commit history:
- [Git guide](http://zulip.readthedocs.io/en/latest/git-guide.html)
- [working copies](https://github.com/zulip/zulip-gci/blob/master/docs/working-copies.md)
- [fixing commits](https://github.com/zulip/zulip-gci/blob/master/docs/fixing-commits.md)

I'm going to leave this PR open for some time, so you can practice :)

**Comment by william1835** [comment]
@trueskawka Hi there, thanks for the reply. I had already found out how to before your reply, but thanks any way. Here's the commit, squashed down.

**Comment by trueskawka** [comment]
Cool. I'm closing this PR since the file got moved in a different commit :)

https://github.com/zulip/zulip-gci/commit/26ff9c8605d4429f8523559d3ef96b5737e6f788

Thanks for improving @william1835!

**Pull request closed without merging**
