### PR TITLE
interactive bots: Run the followup bot for anamarsabi

### PR DESCRIPTION
**Pull request by anamarsabi**
https://codein.withgoogle.com/dashboard/task-instances/6676872215658496/

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@anamarsabi, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by feorlen** [comment]
Hi @anamarsabi, your notes and screenshots look great. Although for this task there should be only one commit. You can squash all your individual commits into one with an interactive rebase. If you need some help with that, you can read about it in the docs, or ask in chat. http://zulip.readthedocs.io/en/latest/git-guide.html#examine-and-tidy-your-commit-history

**Comment by isht3** [comment]
Good work on completing this task! Your task is approved. :smile:

**Comment by trueskawka** [comment]
Hi @anamarsabi!

Could you change your filenames to not have whitespaces, as per task description? I think it'll be ready to merge then.

**Pull request closed without merging**
