### PR TITLE
integrations: Add screenshots and notes for Stripe

### PR DESCRIPTION
**Pull request by Bickio**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@Bickio, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by trueskawka** [comment]
Hi @Bickio!

This looks great! I'm sorry you've encountered problems with the full account.

Could you clean up your commit history? All the changes should be in one commit. Thanks!

**Comment by Bickio** [comment]
Ok. It should be one commit now.

**Comment by showell** [comment]
Thanks, @Bickio, merging!

**Pull request merged**
