### PR TITLE
Submit a Pull Request

### PR DESCRIPTION
**Pull request by YagoGG**
Create directory `/submit-a-pull-request/YagoGG` with an introductory file in it.

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@YagoGG, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by YagoGG** [comment]
Just signed it. Thank you!

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@YagoGG, thanks for signing the CLA!

**Comment by trueskawka** [comment]
Hi @YagoGG!

Good job! Merging.

**Comment by YagoGG** [comment]
Thank you, @trueskawka!

**Pull request merged**
