### PR TITLE
Submit a pull request

### PR DESCRIPTION
**Pull request by arnavaghav**
Because I created a file directly int the submit-a-request, I had to delete it, therefore I have 4 commits. Sorry.

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@arnavaghav, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by reyha** [comment]
Hi @arnavaghav. You need to have only 2 commits in your PR as per your task description. Please go ahead and clean your commit history. See https://github.com/zulip/zulip-gci/blob/master/docs/fixing-commits.md  for more details.

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@arnavaghav, thanks for signing the CLA!

**Comment by krtkmj** [comment]
Please squash your commits into two and fix your commit messages.

**Pull request closed without merging**
