### PR TITLE
Submit a pull request

### PR DESCRIPTION
**Pull request by tuddor1234**
Hi, guys! :tada:

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@tuddor1234, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by pweaver** [comment]
@tuddor1234 Thanks for submitting this!!

It looks like the whole task got done in one commit and the second change to commit it is empty? (It looks like there is an empty commit which is weird. Did you do this on the Github editing interface?) Plus there are a couple of extra commits which we want to remove.

There are a couple of ways to fix this.
Since this is pretty small the easiest would probably be to delete the branch and recreate it.

If you are doing it from the command line you can do an interactive rebase to remove the old commits.

The more advanced approach
`git rebase -i HEAD~5` # This does an interactive rebase of the last five commits.
and then delete the lines of the commits you don't need and edit the ones which need to be changed.

You can then use `git push -f` to push the changes

See https://zulip.readthedocs.io/en/latest/git-guide.html for more details.

**Comment by pweaver** [comment]
You will also need to sign the dropbox CLA before we approve any tasks.

**Comment by pweaver** [comment]
The rebase option is probably a larger hammer than you need for this.
You can also ask questions on the Zulip GCI help chat.

**Comment by trueskawka** [comment]
Hi @tuddor1234!

How's you work going? This guide on fixing your commits might be useful - https://github.com/zulip/zulip-gci/blob/master/docs/fixing-commits.md.

Have you claimed and submitted the task in the GCi app?

**Comment by trueskawka** [comment]
Hi @tuddor1234!

I'm closing this PR, since we haven't heard from you for quite some time.

If you want to still do this task, please reclaim it in the GCI app and comment in this thread so we can reopen the PR.

Thanks :)

**Pull request closed without merging**
