### PR TITLE
interactive bots: Run the links bot for 1Niels

### PR DESCRIPTION
**Pull request by 1Niels**
Hey, I added my notes and screenshots for the task. Furthermore, I fixed a minor typo on the task page. Thanks!

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@1Niels, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by vaibhavsagar** [comment]
Hi @1Niels, a separate pull request fixed that typo. Can I get you to `rebase` and remove it from your pull request?

**Comment by 1Niels** [comment]
Hey @vaibhavsagar, sure no problem! The pull request should be ready now, thanks!

**Comment by umairwaheed** [comment]
@1Niels, looks good. There is an extra 's' in `@resource` screenshot :) though but it's not a biggie. Merging this!

**Pull request merged**
