### PR TITLE
interactive bots: Run the links bot for Bickio

### PR DESCRIPTION
**Pull request by Bickio**
All straight forward and working

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@Bickio, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by umairwaheed** [comment]
@Bickio can you please also include in the screenshot the output of `@links`. It would be great if you could include the streams from where the messages were sent. Thanks.

**Comment by Bickio** [comment]
Done.

**Comment by umairwaheed** [comment]
Thanks @Bickio. Merging this now!

**Pull request merged**
