### PR TITLE
bot avatars: Add avatars from internet sources.

### PR DESCRIPTION
**Pull request by 540KJ**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@540KJ, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by trueskawka** [comment]
Hi @540KJ!

Thanks for working on this!

Although many of the bots have a CC license, some of them don't allow derivatives, some don't allow commercial use. Could which license each image is licensed under in the notes? 

In general, the collection of avatars looks quite extensive. Since Zulip avatars are small and square, I think adding the avatars resized to 50x50px would give us some idea how they could look when used as avatars. Could you add those?

Thanks!

**Comment by YagoGG** [comment]
Hey, @540KJ! Hope you're doing well.

Do you still want to pursue this PR's merging?

**Comment by YagoGG** [comment]
Closing this due to inactivity.

Feel free to ping us if you're still interested in working in this PR. Thanks!

**Pull request closed without merging**
