### PR TITLE
Sumbit a pull request

### PR DESCRIPTION
**Pull request by mateicristea88**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@mateicristea88, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by reyha** [comment]
@mateicristea88  Your code looks good. Please change your commit messages to read ``Add hello-world.md`` and ``hello-world.md: Change username to GitHub handle `` as per the task description. Kindly let us know if face any difficulty. Thanks!

**Comment by mateicristea88** [comment]
@reyha After a bit of time on google, I can't figure out how to edit those commit messages from within the web interface. I would appreciate any tips from where to start.

**Comment by reyha** [comment]
@mateicristea88  Sure, I'd love to help! Generally to amend the last commit message, you can simply do ``git commit --amend``. But like in you case where you need to modify more than a single commit, you can do an interactive rebase using ``git rebase -i HEAD~2`` . Simply replace ``pick`` with ``reword`` for the commits which you want to modify and push your changes again.

Please see https://help.github.com/articles/changing-a-commit-message/ for more details. Let us know over the Zulip chat if you have any problem.

**Pull request closed without merging**
