### PR TITLE
Submit a pull request

### PR DESCRIPTION
**Pull request by derAnfaenger**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@derAnfaenger, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by derAnfaenger** [comment]
Had a little trouble because of my old pull request that I didn't do in the correct branch: https://github.com/zulip/zulip-gci/pull/86
This explains the multiple adds and deletes.

**Comment by TomaszKolek** [comment]
Answer on chat ;-)
Needs more work

**Comment by TomaszKolek** [comment]
We need to see here 2 commits (not more, not less) please read it: https://github.com/zulip/zulip-gci/blob/master/docs/fixing-commits.md and try to do require operations ;-)

Don't hesitate to ask.

**Pull request closed without merging**
