### PR TITLE
interactive bots: Run the links bot for lonerz.

### PR DESCRIPTION
**Pull request by lonerz**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@lonerz, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by trueskawka** [comment]
Hi @lonerz!

Have you claimed and submitted this task in the GCI app? I can't see it under your "completed" or "in progress" tasks.

If you did, could you link it here? Thanks!

**Comment by lonerz** [comment]
@trueskawka yep! https://codein.withgoogle.com/dashboard/task-instances/6208290906177536/

**Comment by hackerkid** [comment]
> **messages sent to the bot in the devel and social streams**

Did you miss this?

**Comment by lonerz** [comment]
@hackerkid It seems like they just updated the task. I finished this 3 days ago, so no I haven't taken those screenshots. I will repost them..

**Comment by lonerz** [comment]
@hackerkid fixed and updated.

**Comment by umairwaheed** [comment]
Looks good! Merging this.

**Pull request merged**
