### PR TITLE
integrations: Add notes for HomeAssistant

### PR DESCRIPTION
**Pull request by Bickio**
This integration is not possible due to lack of webhook support. Cheers

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@Bickio, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by umairwaheed** [comment]
@Bickio, so you didn't get it to integrate with Slack?

**Comment by umairwaheed** [comment]
(ignore my last comment; just saw your comment)

**Comment by umairwaheed** [comment]
@Bickio, I think that Home Assistant and Slack integration is possible. https://home-assistant.io/components/notify.slack/.

**Comment by Bickio** [comment]
Yes. It is possible, but the connection is done through one of the HomeAssistant APIs (not webhooks). The integration is still possible, but beyond the scope of GCI and probably not worth the time. This was pointed out in the notes.md file. This is the same situation as one of my other research tasks (https://github.com/zulip/zulip-gci/pull/194).
I don't think that it's worth testing slack's integration until at this stage, as it is not a web app and would therefore require a local install, and I don't own any IOT devices to test it with. The main reason though, is that HomeAssistant doesn't support webhooks.

Hope that makes sense!
Cheers,
Bickio

**Comment by trueskawka** [comment]
Hi @Bickio!

What's the status of this PR? Has your GCI task been accepted or abandoned?

**Comment by Bickio** [comment]
Hi @trueskawka!
My task has indeed been accepted. 
You may still want to merge this with master to deter other students from attempting the later tasks for homeassistant. Up to you.
Cheers,
Bickio

**Comment by trueskawka** [comment]
Cool, merging! 

Thanks, @Bickio!

**Pull request merged**
