### PR TITLE
Reference python-zulip-api dev env in interactive-bots.md.

### PR DESCRIPTION
**Pull request by roberthoenig**

### CODE REVIEW

**Comment by roberthoenig** [comment]
Merging this without review since it's short and will help new people claiming the bots task. Post-merge reviews are appreciated :)

**Comment by abhijeetkaur** [comment]
@roberthoenig I understand the requirement for this, as 'zulip_bots' doesn't run off the latest code. Also both the students who have completed this have faced the same issue. But I don't think I completely understand where do we want the students to run python-zulip-api virtualenv, within the zulip dev vagrant env?

Do they have to run `pip uninstall zulip_bots`?

**Comment by roberthoenig** [comment]
@abhijeetkaur once they are in the python-zulip-api dev environment, they don't have to run `pip uninstall zulip_bots` anymore (I just recommended this as a step to a student since it avoids recursions of this problem if they're outside of the dev env.)

Students should activate the venv wherever they are running bots. I'm not exactly sure if and how we should add this info.

**Comment by abhijeetkaur** [comment]
Will it work well if they activate the venv separately in another terminal, and then run zulip-run-bot command in vagrant?? I don't think this is the case or is it?

My main question is that do we need to activate venv within vagrant? (The answer to which I think is yes, as vagrant is separate from rest of the machine, but that seems a bit odd)

**Comment by roberthoenig** [comment]
Right, so you need to activate the venv for each terminal separately. You need to activate it in the terminal and environment you will use to execute zulip-run-bot. I'm not sure if running bots inside Vagrant works, I think we had some issues with that last year. What do you suggest should we add to the docs to make this more clear?

**Comment by abhijeetkaur** [comment]
Yes! Definitely, we should add it to the docs for sure.

**Comment by roberthoenig** [comment]
Agreed. Do you have any suggestions on how we should phrase it? I'm missing some specific failures that tell where our docs are not comprehensive enough.

**Pull request merged**
