### PR TITLE
Devansh mehra/zulip gci

### PR DESCRIPTION
**Pull request by DevanshMehra**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@DevanshMehra, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by vaibhavsagar** [comment]
Hi @DevanshMehra, this needs a little more work. Your second commit message is slightly different from the instructions, your branch isn't named `submit-a-pull-request`, and your pull request title is different from what we expect. Can you try this again? I think you might need to make a new pull request. Thanks :smile:

**Comment by DevanshMehra** [comment]
Thanking For telling @vaibhavsagar  requested the new pull request

**Comment by krtkmj** [comment]
Closing this PR. See #73

**Pull request closed without merging**
