### PR TITLE
hello-world.md: Change username to GitHub handle.

### PR DESCRIPTION
**Pull request by anirudhjain75**
Hey I guess i just finished it

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@anirudhjain75, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by sonali0901** [comment]
@anirudhjain75  Hey, it is great that you are working on it. Some things to look out for- the file name should have extension .md . Also carefully go through https://github.com/zulip/zulip-gci/blob/master/tasks/submit-a-pull-request.md to check the file name too. The 'I am __' I must be in capitals. Try to edit the same PR rather than going for new ones. 
Feel free if you need any help!

**Comment by anirudhjain75** [comment]
@sonali0901 Hey I guess its fine now

**Comment by sonali0901** [comment]
@anirudhjain75  Great!! We are getting closer to a successful completion. I would encourage you to read the task description carefully and figure out minor yet important things like `hello-world.md` and not `Hello-World.md` . Also as the number of commits are more than 2 now, read a little bit about `interactive rebase` and `force push`.( `git rebase -i HEAD~X` (where X is a number) and `git push --force ` for changing the commits done and then updating you PR, respectively)

**Pull request closed without merging**
