### PR TITLE
interactive bots: Run the links bot for ThirstyMOE. 

### PR DESCRIPTION
**Pull request by ThirstyMOE**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@ThirstyMOE, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by TomaszKolek** [comment]
Firstly you need to squash your commits into one. Our tutorial should help https://github.com/zulip/zulip-gci/blob/master/docs/fixing-commits.md

**Comment by umairwaheed** [comment]
@ThirstyMOE, your code is good to merge but your commit message should be just " interactive bots: Run the links bot for ThirstyMOE."

**Comment by TomaszKolek** [comment]
Merged and approved

**Pull request merged**
